### ISSUE TITLE
Add support for Kotlin

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [krasa/EclipseCodeFormatter#101]
Kotlin is Jetbrain's old new language for the JVM. It recently hit 1.0 release, and is replacing Java in some spaces at a decent pace.

The grammar is quite similar to Java's, but the current fmt is based off Java IntelliJ, which is not opinionated about blank lines and such, so maybe the existing formatter could be tweaked to work with Kotlin.

**Comment by krasa** [comment]
Are you telling me that JetBrains, made incompatible formatters for Kotlin? They made an effort to make Java formatters compatible, I don't see why they would not make it for Kotlin also.
Is it reported on youtrack?

**Comment by FranciscoE-Hudl** [comment]
The formatter is there, it's just based the Java one, which AFAIK it's not configurable and doesn't remove blank lines, doesn't have max line size, or allow changing parenthesis/brackets strategy.
