### ISSUE TITLE
Import order issue

### ISSUE THREAD

**Issue by a14n** [krasa/EclipseCodeFormatter#104]
With the following `file.importorder` :

```
3=\#com
2=com
1=\#com.mycorp
0=com.mycorp
```

The output with plugin _15.6.132.637.1_ is :

```
import static com.google.common.base.MoreObjects.firstNonNull;

import com.mycorp.DateUtils;
```

but should be (like in eclipse) :

```
import com.mycorp.DateUtils;

import static com.google.common.base.MoreObjects.firstNonNull;
```

**Comment by ccsplit** [comment]
I am having this same issue. I believe this may be related to #97 which has been fixed within master but hasn't been released yet. I haven't had a chance to test with master as of yet, but will update if this resolves the issue. 

As a workaround I found that you can add your imports to the manual configuration as `com.mycorp;\#com.mycorp;com;\#com;` and it should resolve the issue.

**Comment by krasa** [comment]
It was released, this is probably some other problem.

**Comment by krasa** [comment]
It was indeed related to #97, I changed method of loading the file, and it did something unexpected...

**Comment by a14n** [comment]
I just test against _15.7.132.637.1_ and I still see the issue using _Import order from file_ (althought it's ok with _Import order with manuel configuration_)

**Comment by krasa** [comment]
As sorry, not it should be ok.

**Comment by a14n** [comment]
Thanks :)
