### ISSUE TITLE
Import order with upper case packages

### ISSUE THREAD

**Issue by andborg** [krasa/EclipseCodeFormatter#105]
Given a package structure like this:

```
./importorder/example
./importorder/example/root
./importorder/example/root/BFoo.java
./importorder/example/root/A
./importorder/example/root/A/AFoo.java
./importorder/example/root/CFoo.java
./importorder/example/Main.java
```

 Eclipse Mars.2 Release (4.5.2) formats Main.java like this:

```
package importorder.example;

import importorder.example.root.BFoo;
import importorder.example.root.CFoo;
import importorder.example.root.A.AFoo;

public class Main
{
    public static void main(String[] args)
    {
        new AFoo();
        new BFoo();
        new CFoo();
    }
}

```

IntelliJ IDEA 2016.1.3 with Eclipse Code Formatter 15.7.132.637.2, like this:

```
package importorder.example;

import importorder.example.root.A.AFoo;
import importorder.example.root.BFoo;
import importorder.example.root.CFoo;

public class Main
{
    public static void main(String[] args)
    {
        new AFoo();
        new BFoo();
        new CFoo();
    }
}

```

**Comment by krasa** [comment]
What is your import order setings? can you upload your example?

**Comment by andborg** [comment]
I have import order specified in a file that contains this:

```
#Organize Import Order
#Tue May 03 11:15:04 CEST 2016
3=com
2=org
1=javax
0=java
```

I'll attach the example project here. 
[import-order-example.tar.gz](https://github.com/krasa/EclipseCodeFormatter/files/359115/import-order-example.tar.gz)

**Comment by krasa** [comment]
Thank you! You can test it, if you want:
https://github.com/krasa/EclipseCodeFormatter/releases/download/15.8.132.637.0/EclipseFormatter.zip

**Comment by andborg** [comment]
Tested and works on the real problem project too. Thanks!
