### ISSUE TITLE
Javadoc formatter splits line on punctuation marks

### ISSUE THREAD

**Issue by elrodro83** [krasa/EclipseCodeFormatter#111]
When applying the formatter on javadoc, eclipse keeps together the punctuation mark (like dot or comma) with the previous word. For instance, if i have a max line width of 10, the following code:

```
 * abc efg.
```

is formatted in eclipse to 

```
 * abc
 * efg.
```

while the plugin changes it to

```
 * abc efg
 * .
```

I'd expect the formatting of the plugin to be consistent with what eclipse does.

**Comment by krasa** [comment]
The plugin is consistent, it just depends on eclipse version, and config.

**Comment by elrodro83** [comment]
In eclipse, i'm using neon, and on idea i tried with version 15.8.132.637.1 and 15.9.132.637.0, all with the same config file, and got the reported difference.

**Comment by krasa** [comment]
And did you set `custom eclipse location` in the settings to your eclipse?

**Comment by elrodro83** [comment]
Just tried that. When setting the custom eclipse location to a Neon installation the formatting is as expected.
Are there any plans to include Neon support in the plugin? Or at least to have to configure just the relevant libraries instead of a full eclipse installation?

**Comment by krasa** [comment]
Yes, there are plans.  You copy 
```
org.eclipse.core.contenttype_3.5.100.v20160418-1621.jar
org.eclipse.core.jobs_3.8.0.v20160509-0411.jar
org.eclipse.core.resources_3.11.0.v20160503-1608.jar
org.eclipse.core.runtime_3.12.0.v20160606-1342.jar
org.eclipse.equinox.app_1.3.400.v20150715-1528.jar
org.eclipse.equinox.common_3.8.0.v20160509-1230.jar
org.eclipse.equinox.preferences_3.6.0.v20160120-1756.jar
org.eclipse.jdt.core_3.12.0.v20160516-2131.jar
org.eclipse.osgi_3.11.0.v20160603-1336.jar
org.eclipse.text_3.6.0.v20160503-1849.jar
```
into a directory and use that.

**Comment by krasa** [comment]
Done.
