### ISSUE TITLE
Search path for JAR file is wrong

### ISSUE THREAD

**Issue by kaldonia** [krasa/EclipseCodeFormatter#113]
Plugin Version: 15.8.132.637.1

CLion is running on linux from a central installation in /opt/clion-2016.2 where the plugin is installed as well. Setup and using the plugin is possible, but when formatting, this error occurs:

> Plugin jar file not found: /home/user/.CLion2016.2/config/plugins/EclipseFormatter/lib/adapter45.jar

Adding a link fixes the problem:
> ~/.CLion2016.2/config/plugins$ ln -s /opt/clion-2016.2/plugins/EclipseFormatter/ .

Seems that adding an additional search path pointing to the plugin dir of the running clion instance could possibly fix this issue.

**Comment by krasa** [comment]
Is that some custom preconfigured IDE installation in your company?
I think I could add some support for that.

**Comment by kaldonia** [comment]
No, nothing special. Simply untared to a central location on a shared development server used by all developers.

**Comment by krasa** [comment]
Fixed and released.
