### ISSUE TITLE
pathToConfigFile doesn't accept paths with $PROJECT_DIR$

### ISSUE THREAD

**Issue by Rhygon** [krasa/EclipseCodeFormatter#116]
I found an old issue [here](https://github.com/krasa/EclipseCodeFormatter/issues/47) which talks about setting up this value.

But it doesn't seem to work in the same way for me.

I found the eclipseCodeFormatter.xml file which confusingly works alongside the misc.xml. But two things:
1. When setting this path via the IDE it inconsistent with which xml file is updated, and then can save the absolute path in the files.
2. The IDE formatter file location does not accept $PROJECT_DIR$ even though that's what it saves to file.

And then you set it all up and then when you open another project, it then uses the formatter from the last project you set up, and then can save that to eclipseCodeFormatter.xml. It doesn't know what itis doing.

But misc.xml has to be under source control beacuse it mixes project and user settings..., so this is frustrating.

**Comment by krasa** [comment]
Yeah, it's fucked up.

**Comment by krasa** [comment]
Project specific profile was introduced, misc.xml is no longer used.
