### ISSUE TITLE
How about spring xml files'format?

### ISSUE THREAD

**Issue by xinkunZ** [krasa/EclipseCodeFormatter#118]
Intellij Idea xml format rule is different from eclipse, For example,in IJ's settings xml file width default value is 120, it is same as eclipse settings.In a spring xml, if my spring bean's class name is longer than 120,the class attribute will be wraped to next line,but in eclipse, the class attribute won't be warped, and eclipse xml formatter will warp next attribute like 'scope' or 'lazy-init' to next line.

**Comment by xinkunZ** [comment]
For example,in IJ's settings xml file width default value is 120, it is same as eclipse settings.In a spring xml, if my spring bean's class name is longer than 120,the class attribute will be wraped to next line,but in eclipse, the class attribute won't be warped, and eclipse xml formatter will warp next attribute like 'scope' or 'lazy-init' to next line.

**Comment by xinkunZ** [comment]
I had sent a youtrack: https://youtrack.jetbrains.com/issue/IDEA-160433
There are some format examples

**Comment by krasa** [comment]
I have tried to use xml formatter, but it was not possible, it needed some eclipse platform things at runtime...

**Comment by xinkunZ** [comment]
OH!! That's sounds so so so cruel!!!

**Comment by krasa** [comment]
Yep.
