### ISSUE TITLE
Puglin incompatible with IntelliJ version 2016.1.4

### ISSUE THREAD

**Issue by blaltarriba** [krasa/EclipseCodeFormatter#123]
Hi!

I'm currently using IntelliJ IDEA Community Edition 2016.1.4 and I want to start using this plugin. I downloaded the last version available 16.0.163.3094.

When I try to install I get message: 
"Puglin 'Eclipse Code Formatter' is incompatible with this installation"

Any idea?

**Comment by krasa** [comment]
Yeah, download a compatible one. It is restricted by `COMPATIBLE BUILDS` column.
You need 16.0.132.637

**Comment by blaltarriba** [comment]
It works! Thank you @krasa !
