### ISSUE TITLE
Provide a new version for 2016.3.2

### ISSUE THREAD

**Issue by markiewb** [krasa/EclipseCodeFormatter#124]
Hej @krasa,
please provide a new version here at github and at https://plugins.jetbrains.com/idea/plugin/6546-eclipse-code-formatter, so that I can offically use the recently merged Workspace-Mechanic-Feature https://github.com/krasa/EclipseCodeFormatter/commit/fde1827cf061088e97d17397e1d591647eead604. Thank you!

**Comment by krasa** [comment]
Wait a minute, I thought that you were using Netbeans? :)

**Comment by markiewb** [comment]
Partly correct. Some of my team members want to leave Eclipse. Every IDE is allowed in our team, if the output (the formatted java code) is the same as using Eclipse.

**Comment by krasa** [comment]
https://github.com/krasa/EclipseCodeFormatter/releases/tag/16.1.132.637.0

I will upload it to repo tommorow, after some testing...

**Comment by markiewb** [comment]
The plugin is now available at https://plugins.jetbrains.com/idea/plugin/6546-eclipse-code-formatter/31738-update 

Closing this issue
