### ISSUE TITLE
Use a separate project config file, instead of misc.xml

### ISSUE THREAD

**Issue by krasa** [krasa/EclipseCodeFormatter#133]
It kinda pisses me off when it changes versioned misc.xml in a project which does not use this plugin, 

Opinions?

**Comment by staffanf** [comment]
I would really like this.

**Comment by krasa** [comment]
This should make things better, try it if you want: https://github.com/krasa/EclipseCodeFormatter/releases/download/16.4.132.637.0/EclipseFormatter.zip
