### ISSUE TITLE
//@formatter:off not working for java in intellij 2016.1.4

### ISSUE THREAD

**Issue by maglkp** [krasa/EclipseCodeFormatter#134]
@formatter:off, @formatter:on tags are not working in latest version on the plugin - the entire file is autoformatted. I'm using intellij 2016 but my colleagues reported the same issue on newer versions. I tried both block and line comments 

My settings.xml seem to contain the proper values:
<setting id="org.eclipse.jdt.core.formatter.disabling_tag" value="@formatter:off"/>
<setting id="org.eclipse.jdt.core.formatter.enabling_tag" value="@formatter:on"/>

'enable formatter markers' setting in IDE is also set

**Comment by krasa** [comment]
Works for me. IJ 2017.1.2

**Comment by krasa** [comment]
You need 
```
<setting id="org.eclipse.jdt.core.formatter.use_on_off_tags" value="true"/>
```

**Comment by maglkp** [comment]
Works. Awesome, thanks!
