### ISSUE TITLE
plugin ignores @formatter:off and  @formatter:on

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [krasa/EclipseCodeFormatter#135]
the plugin is ignoring this subsequence... the result in my case is that some javadocs have become completely unreadable. I already turned the option on that IntelliJ should not ignore this sequence and if I disable eclipse code formatter IntelliJ does ignore it. 

please fix...

**Comment by krasa** [comment]
what?

**Comment by Captain-P-Goldfish** [comment]
I mean the

// @formatter:off
...
// @formatter:on

notation is completely ignored by this plugin. This leads to problems in some of our projects. Would be great if support is added.

**Comment by krasa** [comment]
https://github.com/krasa/EclipseCodeFormatter/issues?utf8=%E2%9C%93&q=%40formatter%3Aoff
