### ISSUE TITLE
Unable to use multiple Eclipse formatting files

### ISSUE THREAD

**Issue by IvanMwiruki** [krasa/EclipseCodeFormatter#136]
My team is using Eclipse Workspace Mechanic and they use multiple .epf and .xml files for formatting. I'm trying to accomplish the same thing in Intellij and found this plugin. Unfortunately, it looks like I can only use 1 .epf or .xml file at once. 

How can this plugin be made to support multiple config files?

**Comment by krasa** [comment]
By implementing it. :-)

**Comment by markiewb** [comment]
I do not understand. Two files in different file types at the same time?
If both files define the formating, which should be used? Please give more
details!

Den 3 maj 2017 7:55 em skrev "Ivan Mwiruki" <notifications@github.com>:

**Comment by IvanMwiruki** [comment]
These are the workspace mechanic files that my team is using. They're all being used at the same time. Hope this helps. 

![screen shot 2017-05-03 at 2 27 35 pm](https://cloud.githubusercontent.com/assets/13284085/25682383/d9e86882-300c-11e7-8d8e-1ccef02d84a7.png)

**Comment by markiewb** [comment]
Look in the epf files!  Only those with /instance/org.eclipse.jdt.core are
relevant for this plugin. I guess only one file remains. Then you have to
check whether the xml file has the same configuration entries like the epf
file (without the /instance/-prefix)!

At least in our epf configs at work the entries of the XML file are
duplicated in there AND even the XML file is embedded in the epf (the
longest line of all). This depends of course on which entries have been
accepted to be exported after recording with WSM.

PS: If you want to have save actions or other refactoring-based cleanups,
you will have to go for the plugin
https://plugins.jetbrains.com/plugin/7642-save-actions which at least
provides the most common ones.

Den 3 maj 2017 11:29 em skrev "Ivan Mwiruki" <notifications@github.com>:

**Comment by IvanMwiruki** [comment]
I'll try the save actions plugin for the "save-actions.epf" file. 

There are actually multiple files with "/instance/org.eclipse.jdt.core": compile-checkstyle.epf, compiler-warnings.epf,  java-formatter.epf, javadoc-errors.epf. Should I just compile these into 1 file? 

The xml file is full of "org.eclipse.jdt.core.formatter..." tags. Could you show how you have the xml file imbedded in the .epf file?

Then there are a few .epf files with "/instance/org.eclipse.jdt.ui". What can be done about these? 

Thanks.

**Comment by markiewb** [comment]
I think combining the epfs is not necessary. This plugin only supports

/instance/org.eclipse.jdt.core/

Check again!

After removing this prefix at runtime, the formatter engine is feed with
the key-value map as configuration. I contributed  the pull request back
then, so that's why I know the details. There is no official Eclipse
documentation about which entries are related to formatting, but I guess
all those contain "formatter" in their name like
 "org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_package"
are good candidates.

https://github.com/krasa/EclipseCodeFormatter/issues/73

Den 4 maj 2017 9:36 em skrev "Ivan Mwiruki" <notifications@github.com>:

**Comment by IvanMwiruki** [comment]
It seems you answered the 1st question but not the last 2.

**Comment by markiewb** [comment]
>Then there are a few .epf files with "/instance/org.eclipse.jdt.ui". What
can be done about these?

Such entries are ignored

Den 6 maj 2017 8:23 fm skrev "Ivan Mwiruki" <notifications@github.com>:

**Comment by krasa** [comment]
Solved?
