### ISSUE TITLE
How to use EclipseCodeFormatter in my plugin with java code?

### ISSUE THREAD

**Issue by xinkunZ** [krasa/EclipseCodeFormatter#138]
Is there any way to use eclipse code formatter in plugin code to format a PsiClass??
I just use ```CodeStyleManager.getInstance(project).reformat(psiClass);```  but it looks like formatted by IDEA's formatter, not eclipse code formatter...
I hope you will help me...

**Comment by krasa** [comment]
Only these methods use the Eclipse formatter (if it is enabled): https://github.com/krasa/EclipseCodeFormatter/blob/57b413717c9ac6a204d9b86c85b8d6098b2b6b8d/src/java/krasa/formatter/plugin/EclipseCodeStyleManager.java#L64-L86
