### ISSUE TITLE
Format by IDEA with this exception

### ISSUE THREAD

**Issue by xinkunZ** [krasa/EclipseCodeFormatter#139]
EclipseCodeFormatter have a option:[format other file types by intellj ...]
I have input "xml;" in this settings,When I format code in a xml file, IDEA's format seems not work, what should I do? or is there any other settings I haven't noticed ?

**Comment by krasa** [comment]
Works as intended.

"Format other file types by IntelliJ with this exception:" - means (or at least I hope so) that IntelliJ will format everything but that what you add there.
