### ISSUE TITLE
Support for Eclipse 4.7 Oxygen 

### ISSUE THREAD

**Issue by markiewb** [krasa/EclipseCodeFormatter#144]
https://www.eclipse.org/oxygen/

And of course there are changes in the formatter https://www.eclipse.org/eclipse/news/4.7/jdt.php#JavaFormatter

**Comment by krasa** [comment]
Done. Only C++ formatter from 4.7 no longer works, I will probably just delete it, it was bugged anyway.

**Comment by krasa** [comment]
Done

**Comment by dodgex** [comment]
Hey @krasa any idea when a new version with this fix is released?

Thanks in advance and thank you for this awesome plugin! ❤️

**Comment by krasa** [comment]
It was released 07.07.2017

**Comment by dodgex** [comment]
Oh nice, sorry for asking then. After seeing that the plugin now has the new formatter I just checked the [releases page](https://github.com/krasa/EclipseCodeFormatter/releases) on github where the release is not listed.

Again thanks alot. Looking forward for getting back to my Intellij based project to test the new version.

**Comment by krasa** [comment]
Yeah, I use primarily https://plugins.jetbrains.com/idea and Github releases only for testing.
