### ISSUE TITLE
Javadoc indent broken after hitting return in first line

### ISSUE THREAD

**Issue by mp911de** [krasa/EclipseCodeFormatter#145]
Used versions:
IntelliJ: 2017.2 RC2 (172.3317.53)
Plugin version: 17.0.132.637.1

Steps to reproduce:

1. Have a Java type with Javadoc
2. Place caret in first line (directly after `/**` )
3. Hit enter

Symptom: Whitespace before the asterisk in the next line is removed
Expected behavior: Use same indentation as the first line.

Looks like:

Before hitting enter:

```
/**
 *
 */
public interface MyClass {}
```

After:

```
/**
*
 *
 */
public interface MyClass {}
```

**Comment by krasa** [comment]
Thanks! You can update.

**Comment by mp911de** [comment]
Thanks for the fast response! Awesome!
