### ISSUE TITLE
Keep bundling Eclipse 4.6 Neon formatter for compatibility

### ISSUE THREAD

**Issue by fmthoma** [krasa/EclipseCodeFormatter#146]
Since there are breaking changes between 4.6 and 4.7, it would be good to have Eclipse 4.6 support bundled. In particular, when using [Spotless](https://github.com/diffplug/spotless) in conjunction with this plugin, it is currently not possible to get a consistent coding style out of the box (Spotless does not yet offer 4.7 support, while EclipseCodeFormatter has already dropped 4.6 support).

**Comment by fmthoma** [comment]
Example that is formatted differently between 4.6 and 4.7:

```xml
…
<setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_method_invocation" value="48"/>
…
```

Eclipse 4.6:
```java
foo(bar(
        baz,
        quux));
```
Eclipse 4.7
```java
foo(
        bar(
                baz,
                quux));
```

**Comment by krasa** [comment]
There are always breaking changes... But you should be able to specify Eclipse 4.6 location.

**Comment by fmthoma** [comment]
> There are always breaking changes...

@krasa I haven't found any between the different 4.6.x versions, and 4.4 is bundled as well for compatibility.

> But you should be able to specify Eclipse 4.6 location.

Yes, that works. However, this woud force my entire team to install Eclipse alongside with IntelliJ just to have consistent code formatting, which is something I'd like to avoid if possible.

That said, is there a possibility for installing (and using) just the Eclipse formatter without the entire Eclipse SDK? Also, #80 likely would be a solution to this, is there any progress?

**Comment by fmthoma** [comment]
@krasa Oh, I just saw that you released a new version of the plugin with the Eclipse 4.6.3 formatter backported... That was fast! Thank you, helps a lot!

**Comment by krasa** [comment]
Since #80  I was able to shrink the size in half, so I did not do it. But perhaps I could add a possibility of downloading older jars, backporting sucks.
