### ISSUE TITLE
Chained method call wrap

### ISSUE THREAD

**Issue by sergiupantiru** [krasa/EclipseCodeFormatter#147]
Hello,

This is not an actual issue, more a missing functionality. Is it possible to add the "Wrap always" on the chained method calls? 

![image](https://user-images.githubusercontent.com/12131904/28559071-383f5578-7115-11e7-96f6-94ec0c3a5e09.png)

Regards,
Sergiu

**Comment by krasa** [comment]
Add where? Into the Eclipse's formatter? No.

**Comment by sergiupantiru** [comment]
Yes in the Eclipse Formatter. Right now you have to do the multi line manually (and disable wrap).
