### ISSUE TITLE
Java formatter version is not saved when IDEA restarts

### ISSUE THREAD

**Issue by danielestevez** [krasa/EclipseCodeFormatter#148]
In **Eclipse Code Formatter** settings you can change **Java formatter version** to Luna or custom. This works when you exit settings with Apply or OK but next time IDEA is restarted (gracefully or not) Eclipse Formatter is set to default 4.7 Oxigen formatter.

This is troublesome since you need to remember to set this anytime you start IDEA and sometimes it's too late and you get badly formatted files.

IDEA 2017.2.1 

Thanks!

**Comment by krasa** [comment]
Sorry, I deleted a little bit too much of the code before :(

**Comment by danielestevez** [comment]
Thanks! i took a look at the code and yeah i couldn't find anything that saved the settings!
