### ISSUE TITLE
why i have to reconfigure the config of the code formatter when i start a new project 

### ISSUE THREAD

**Issue by gdutjason** [krasa/EclipseCodeFormatter#149]
so, i think once i configured the config then it will be the default config of idea, but it doesn' work. every time i start a new project i must reconfigure again for the new. i think it is troublesome.  maybe the user can choose config all project or config this project. thanks

**Comment by krasa** [comment]
you can configure it for a default project, when you close all projects

**Comment by gdutjason** [comment]
i have a try ,thanks
