### ISSUE TITLE
Do not format other file types by Intellij formatter

### ISSUE THREAD

**Issue by hredondo** [krasa/EclipseCodeFormatter#153]
Hi,

I am facing an issue where we want eclipse formatter to format java files. But avoid that in any other case. So we expected to have that done with the option: "Do not format other file types by Intellij formatter". 

We have it enabled and other type of files like xml are being reformated. 

Something we are missing or it is a bug?

Thanks!

**Comment by markiewb** [comment]
Try the the exclude/include configuration of the plugin!

Den 14 nov. 2017 4:36 em skrev "hredondo" <notifications@github.com>:

**Comment by krasa** [comment]
Oh yeah, that's a bug.

**Comment by markiewb** [comment]
Ohhh. Sorry. Please forget my previous post. I thought the reported issue
was in another plugin.

Den 14 nov. 2017 7:04 em skrev "Vojtěch Krása" <notifications@github.com>:

**Comment by krasa** [comment]
You can try it: https://github.com/krasa/EclipseCodeFormatter/releases/tag/17.3.132.637.0.Eclipse_4.7
I will release it later.

**Comment by hredondo** [comment]
It works! Thank you so much @krasa
