### ISSUE TITLE
Java Stream API formatting

### ISSUE THREAD

**Issue by MaximStepanov** [krasa/EclipseCodeFormatter#157]
Hello,

I stumbled into a problem - when I try to use your plug-in on streams it recognizes them as a simple method chain.  So it append all stream() methods into one line.

Example:
Before using code style settings 
```
someThings.addAll(responce.getThings().stream()
            .map(thing -> mapThingToThought(thing, rule))
            .collect(Collectors.toList()));
```

After:
```
someThings.addAll(responce.getThings().stream()
            .map(thing-> mapThingToThought(thing, rule)).collect(Collectors.toList()));
```

I suggest to make your plug-in able to recognize streams and make methods line splitting.

**Comment by krasa** [comment]
Does Eclipse itself format that way?

**Comment by MaximStepanov** [comment]
I use it in IntellijIDEA

**Comment by krasa** [comment]
So you want me to change Eclipse's formatter so it format's differently than Eclipse, totally defeating the purpose of this plugin?

**Comment by MaximStepanov** [comment]
Don't understood you at all, streams in most of cases that I saw looks like 
stream()
  .filter(..)
  .findFirst()
  .collect()
nor like this
stream().filter(..).findFirst().collect()

Why should Eclipse write that in one line anyway?

**Comment by markiewb** [comment]
Some clarification: This plugin embeds the formatter engine of Eclipse.
Configure the formatter in Eclipse as you prefer, export the configuration
and configure this plugin to use that exported configuration file! This
plugin uses the configuration file to feed the embedded engine.


Den 18 jan. 2018 2:39 em skrev "Alone4ik" <notifications@github.com>:

**Comment by markiewb** [comment]
@krasa: No response for over 2 months. Please resolve as invalid.
