### ISSUE TITLE
Enabling EclipseCodeFormatter for all intellij (community) java projects?

### ISSUE THREAD

**Issue by ragebiswas** [krasa/EclipseCodeFormatter#159]
Not an issue, but does anyone know how I can "enable" this formatter along with its settings (for Java formatter file and import-ortder) for all current and future projects?

Otherwise, for every project I need to go to Settings > Eclipse Code Formatter and apply the same steps repeatedly. My current use case is that I'm trying to create a standard intellij build with this formatter and configuration applied, so end users should be able to open the project and be able to see this plugin with proper settings already applied.

Any help would be much appreciated!

**Comment by krasa** [comment]
close all projects and configure default settings

**Comment by ragebiswas** [comment]
Thank you!
