### ISSUE TITLE
Using "_" as number seperator generates output where all is on one line

### ISSUE THREAD

**Issue by Grisu118** [krasa/EclipseCodeFormatter#161]
Expected Formatting output
```java
  public void some() {
    int testInt = 10000;
    for (int i = 0; i < testInt; i++) {
      System.out.println(i);
    }
  }
```

Actual Output when adding _ to 10_000:
```java
  public void some() {
    int testInt=10_000;for(int i=0;i<testInt;i++){System.out.println(i);}
  }
```

idea.log:
> 2018-04-03 14:41:29,650 [ 465212]  DEBUG - ProxyCodeStyleManagerDelegator - invoking overriding {}({})reformatText[PsiJavaFile:TestClasses.java, [(0,191)]] 
> 2018-04-03 14:41:29,651 [ 465213]  DEBUG - CodeStyleManager_IJ_2016_3plus - format TestClasses.java 0 191 
> 2018-04-03 14:41:29,651 [ 465213]  DEBUG - er.plugin.EclipseCodeFormatter - #format 0-191 
> 2018-04-03 14:41:29,651 [ 465213]  DEBUG - er.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen TestClasses.java 
> 2018-04-03 14:41:29,662 [ 465224]  DEBUG - er.EclipseJavaFormatterAdapter - #formatInternal 
> 2018-04-03 14:41:29,662 [ 465224]  DEBUG - er.EclipseJavaFormatterAdapter - #starting to format by eclipse formatter 
> 2018-04-03 14:41:29,665 [ 465227]  DEBUG - er.EclipseJavaFormatterAdapter - reformatting done 
> 2018-04-03 14:41:29,691 [ 465253]  DEBUG - er.plugin.EclipseCodeFormatter - #formatWhenEditorIsOpen done 
> 2018-04-03 14:41:31,691 [ 467253]   INFO - ntellij.analysis.SonarLintTask - Running SonarLint Analysis for 'TestClasses.java' 
> 2018-04-03 14:41:31,906 [ 467468]   INFO - ntellij.analysis.SonarLintTask - SonarLint analysis done 

Eclipse itself formats the file correct

**Comment by krasa** [comment]
That happens when you have incorrect language level.
![image](https://user-images.githubusercontent.com/1160875/39754847-d8490830-52c3-11e8-9435-9c4fb20920e5.png)
