### ISSUE TITLE
Always replace spaces into tab

### ISSUE THREAD

**Issue by warrenzhu25** [krasa/EclipseCodeFormatter#164]
> The formatter always replace my leading spaces into tab. I think it shouldn't do so

[eclipse-code-formatter.txt](https://github.com/krasa/EclipseCodeFormatter/files/1918388/eclipse-code-formatter.txt)

**Comment by krasa** [comment]
Why do you think that? What does Eclipse do?

**Comment by warrenzhu25** [comment]
I see this `<setting id="org.eclipse.jdt.core.formatter.use_tabs_only_for_leading_indentations" value="false"/>` in the file. Do you mean this is right behavior? I don't have Eclipse installed, could you help confirm since it's overkill for this to install Eclipse? Thanks a lot.

**Comment by krasa** [comment]
Yes, it is the right behavior.
