### ISSUE TITLE
Do not format other file types by Intellij formatter (Intellij 2018.1)

### ISSUE THREAD

**Issue by hredondo** [krasa/EclipseCodeFormatter#167]
Hi,

I am facing an issue I posted some time ago. It was resolved but seems it's happening again with new version of Intellij 2018.1. #153 

We want eclipse formatter to format java files, but avoid it in any other case. So we expected to have that done with the option: "Do not format other file types by Intellij formatter".

We have it enabled and other type of files like xml are being reformatted.

Thanks!

**Comment by krasa** [comment]
Oh, I know, I never released it :]

**Comment by hredondo** [comment]
Thanks for your response @krasa 

Do you have plans of releasing that fix?

**Comment by krasa** [comment]
I just released it with updated Eclipse libs to 4.7.3a.
