### ISSUE TITLE
Format Javascript fails

### ISSUE THREAD

**Issue by jsedanoj** [krasa/EclipseCodeFormatter#173]
Hello,

  I am trying to use EclipseCodeFormatter to format javascript code.
  Environment:
* IntelliJ Community 2018.2.1, with EclipseCodeFormatter 18.1.181.000.0-Eclipse_4.7.3a, JRE: 1.8.0_152 
* Eclipse Luna (4.4.2)

  Steps:

1) In Eclipse Preferences / JavaScript / Code Style / Formatter, New, Initialize with Eclipse [built-in], Export and save the .xml file as js.xml. It looks like (also attached below, renamed to .txt to allow attachment):

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="11">
<profile kind="CodeFormatterProfile" name="js" version="11">
<setting id="org.eclipse.wst.jsdt.core.formatter.alignment_for_binary_expression" value="16"/>
<setting id="org.eclipse.wst.jsdt.core.formatter.insert_space_before_opening_brace_in_block" value="insert"/>
[SOME 200 SETTINGS REMOVED FOR BREVITY]
</profile>
</profiles>
```

[js.xml.txt](https://github.com/krasa/EclipseCodeFormatter/files/2377813/js.xml.txt)

2) El IntelliJ EclipseCodeFormatter settings, "Use the Eclipse code formatter", untick Enable Java, tick Enable JavaScript. In "Eclipse javaScript Formatter config file" choose js.xml. "JavaScript formatter profile" fills up with my profile name (so I guess the file is being correctly read). Close with "OK". Other settings as default.

3) Open a JS file of the project. Hit Ctrl-Alt-L (shortcut for Code / Reformat Code) and bubble shows up: `xxxxx.js failed to format with Eclipse code formatter. Probably due to syntax error or wrong configuration file`

  Any idea up to here?

Further test:

4) Ok, if the file is syntax-incorrect, let us simplify it. I clean the js.xml file up to the bare minimum (no settings):

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="11">
<profile kind="CodeFormatterProfile" name="js" version="11">
</profile>
</profiles>
```

  Then, the bubble error says: `xxxxxx.js failed to format with Eclipse code formatter. loading of profile settings failed, profile has no settings elements`

  Is there any working javascript-format.xml for reference so I can evolve from it?

  Is there any log I can inspect for further info?

**Comment by krasa** [comment]
JS formatter is quite old, maybe it does not support your JS file?
I should probably just remove the whole thing...

**Comment by jsedanoj** [comment]
Well... the JS file is... well... a js file. With functions, alerts, for loops and the like. A pretty standard js file for testing.

Sad to hear that you are considering dropping support for javascript formatting, but if it does not work and you cannot provide support for it, it is better dropped, for sure.

**Comment by krasa** [comment]
JavaScript support was removed.
