### ISSUE TITLE
after commit, code is format by intellij-idea, any idea not format?

### ISSUE THREAD

**Issue by myoss** [krasa/EclipseCodeFormatter#178]
# Setting

![jerry_2018-12-18_18-12-15](https://user-images.githubusercontent.com/6986459/50148212-dfb47e80-02f2-11e9-8092-0655dbf56481.jpg)

# usage steps

## step 1: commit file

![jerry_2018-12-18_18-31-03](https://user-images.githubusercontent.com/6986459/50148538-bea05d80-02f3-11e9-9068-51bd86edccbb.jpg)

## step 2: after commit, code is format by intellij-idea, any idea not format?

![jerry_2018-12-18_18-32-41](https://user-images.githubusercontent.com/6986459/50148537-bea05d80-02f3-11e9-992d-883037c56513.jpg)

# IDEA Version

```
IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018
Subscription is active until May 5, 2019
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

# EclipseCodeFormatter Version

```
v18.2.181.000.0-Eclipse_4.9.0
```

**Comment by myoss** [comment]
@krasa can you help me, thanks

**Comment by krasa** [comment]
I will need to debug it...

**Comment by krasa** [comment]
Should be fixed now
