### ISSUE TITLE
Support Formatter control comments

### ISSUE THREAD

**Issue by agos** [krasa/EclipseCodeFormatter#18]
Since EAP 13, Idea supports formatter control comments (see Settings -> Code Style -> General). These allow to suppress code formatting for parts of files.

Right now if eclipse code formatter is active, these comments are ignored.

**Comment by ghusta** [comment]
Thanks !
It was useful.
StackOverflow link to this feature : [How to disable code formatting for some part of the code using comments?](http://stackoverflow.com/questions/3375307/how-to-disable-code-formatting-for-some-part-of-the-code-using-comments)
