### ISSUE TITLE
Remove DonationNagger from the settings

### ISSUE THREAD

**Issue by arogulin** [krasa/EclipseCodeFormatter#185]
I have "Settings Repository" feature enabled in IntelliJ Idea, it syncs all my settings into github repository which other teams use to sync from. This allow us to use the same settings across all teams. Periodically Idea checks if I have any settings changed and commits the change into that repository. Recently I noticed that 99% of commits are about this line:
```
<component name="EclipseCodeFormatterSettings">
    <option name="donationNagger">
      <DonationNagger>
-        <option name="actionsExecuted" value="3877" />
+        <option name="actionsExecuted" value="3902" />
```
Is there a way to exclude this option `actionsExecuted` from the `EclipseCodeFormatterSettings`? Or the whole block of `donationNagger`, since it's specific to a machine and there is no sense in sharing it with other teams.

Thank you!

**Comment by arogulin** [comment]
https://github.com/krasa/StringManipulation has the same issue as well :(

**Comment by krasa** [comment]
Well, that sucks. I will remove it.

**Comment by arogulin** [comment]
That was super quick! Thank you, @krasa, for your awesome work! I hope you will still get donations without that Nagger, I just sent my $10. :)

**Comment by krasa** [comment]
thanks :)
