### ISSUE TITLE
Exception while parsing IntelliJ's LanguageLevel

### ISSUE THREAD

**Issue by Daishy** [krasa/EclipseCodeFormatter#194]
Hi, 

i'm currently trying to use the (absolutly awsome, by the way) EclipseCodeFormatter in a java 13 project. I've enabled the 13-Preview-Language-Level in IntelliJ for the project which unfortunately leads to an exception within the formatter. The responsible code is the following check in JavaCodeFormatterFacade.java:

```
String substring = level.name().replace("_", ".").substring(4);
...
new Double(substring);
```

The passed `com.intellij.pom.java.LanguageLevel` ist probably ` JDK_13_PREVIEW` which leads to the substring `13.PREVIEW`, which is not parsable as `Double`.

An additional `.replace(".PREVIEW", "")` would probably be enough or a switch-case to explicitly handle the language-version (currently untested):

```
switch(level) {
  case JDK_1_3:
  case JDK_1_4:
  case JDK_1_5:
  case JDK_1_6:
  case JDK_1_7:
  case JDK_1_8:
  case JDK_1_9:
    return "1." + level.toJavaVersion().feature;
  default:
    return level.toJavaVersion.feature;
```

Stacktrace of the error:
```
java.lang.NumberFormatException: For input string: "13.PREVIEW"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at java.base/java.lang.Double.<init>(Double.java:625)
	at krasa.formatter.eclipse.JavaCodeFormatterFacade.newCodeFormatter(JavaCodeFormatterFacade.java:69)
```

I currently have no experience building intellij-plugins so i don't know if i actually will get the project to build. But i will check it out tomorrow and create a path, if i succeed.

And again, thank you for the awesome plugin :)

**Comment by krasa** [comment]
I used a new API for that...
