### ISSUE TITLE
this plugin influences the result of "optimize imports"

### ISSUE THREAD

**Issue by AndreSchulzBerlin** [krasa/EclipseCodeFormatter#197]
when using this plugin the result of "optimize imports" is different than expected

**What steps will reproduce the issue?**
1. Configure sort order for imports (Settings > Editor > Code Style > Java > Imports > Import Layout):
`import all other imports`
`<blank line>`
`import static all other imports`
2. enable Eclipse Code Formatter (e.g. [Formatter.xml.txt](https://github.com/krasa/EclipseCodeFormatter/files/3956236/Formatter.xml.txt))
3. create a file with static and non static imports, like
```
import java.util.ArrayList;

import static java.util.Arrays.asList;

public class Debug {

    public static void main(String[] args) {
        asList("a");
        new ArrayList<>();
    }
}
```

**What is the expected result?**
order of imports
```
import java.util.ArrayList;

import static java.util.Arrays.asList;
```

**What happens instead?**
order of imports
```
import static java.util.Arrays.asList;

import java.util.ArrayList;
```

**system:**
```
IntelliJ IDEA 2019.3 (Community Edition)
Build #IC-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1952M
Cores: 12
Registry: 
Non-Bundled Plugins: EclipseCodeFormatter
```

**Comment by krasa** [comment]
Yes, because that's what Eclipse does. 
See `File | Settings | Other Settings | Eclipse Code Formatter | Import order`
