### ISSUE TITLE
Comments differ

### ISSUE THREAD

**Issue by kangarko** [krasa/EclipseCodeFormatter#204]
Hi there,

I followed the steps to export my custom eclipse format as XML then configured this plugin accordingly (https://i.imgur.com/J5mBxRx.png), however I am running into issues that comments are formatted differently on IntelliJ still:

![a](https://i.imgur.com/5nkxCzU.png)

Any help would be appreciated!
Thanks!
Greetings from Slovakia

**Comment by krasa** [comment]
Upload the xml. 
Eclipse version?

**Comment by krasa** [comment]
Also maybe https://github.com/krasa/EclipseCodeFormatter#possible-problems-with-java-formatting
- Trailing spaces inside javadocs are stripped
  - Set `Strip trailing spaces on save` to `None`

**Comment by kangarko** [comment]
Thanks, 

This is caused by IntelliJ removing trailing spaces from inside of /**/ comments.

In my IntelliJ this option is actually on "All" and it removes the space. Eclipse also removes trailing spaces but it retains them when inside of comments.

Could you perhaps make your plugin stop removing trailing spaces inside the comments?

Thanks!

**Comment by krasa** [comment]
No, IntelliJ does that while saving. As I wrote: Set Strip trailing spaces on save to None.

**Comment by kangarko** [comment]
Thanks
