### ISSUE TITLE
Save Actions plugin not working anymore when using Eclipse Code Formatter

### ISSUE THREAD

**Issue by dosomder** [krasa/EclipseCodeFormatter#214]
```
IntelliJ IDEA 2020.1.4 (Community Edition)
Build #IC-201.8743.12, built on July 21, 2020
Runtime version: 11.0.7+10-b765.65 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
```

I am using the plugin "Save Actions" (https://plugins.jetbrains.com/plugin/7642-save-actions) in combination with this plugin. Since version `20.1.201.6668.0-Eclipse_2020-06-JavaOnly` of Eclipse Code Formatter the plugin "Save Actions" does not work anymore (it simply does not apply the formatting rules on save). If I downgrade Eclipse Code Formatter, everything works again. Is there some kind of conflict between the two plugins?

**Comment by krasa** [comment]
I deleted some useless code, maybe I need to add it again.

**Comment by krasa** [comment]
It should work now.

**Comment by dosomder** [comment]
Thanks @krasa it's indeed fixed.
