### ISSUE TITLE
Not supported 2020.3.3 intellij

### ISSUE THREAD

**Issue by llv22** [krasa/EclipseCodeFormatter#223]
> If the formating is different than expected:
> - make sure you are comparing with the same Eclipse version
> - provide a code example (both from Eclipse and from IntelliJ) and settings files 

> What steps will reproduce the issue?

> What is the expected result?

> What happens instead?

> Сonsider attaching a screenshot, screencast, or a code sample when it's hard to articulate the problem.

> Paste information about IDE and OS (it can be copied from Help | About dialog).

> Please use triple backticks ``` before and after the stacktrace block.

**Comment by krasa** [comment]
works fine for me

**Comment by rajmondx** [comment]
@krasa 

I have the same issue, the plugin is activated, using the same profiles as in eclipse but it just doesnt do anything.

It looks like its completely ignored by idea. Iv'e just updated it right now to `20.8.203.000.0-Eclipse_2020-06-JavaOnly`

And yes it worked fine before the updates (bundled eclipse).

**Comment by krasa** [comment]
try enablind debug logging for ```krasa.formatter```

**Comment by rajmondx** [comment]
Thank you for your quick response.

I activated the logs (found so many - different - ways to do it, eg. examples using `#` as prefix for the package, better safe than sorry):

```xml
  <logger name="krasa.formatter">
    <level value="DEBUG"/>
  </logger>

  <category name="#krasa.formatter">
    <priority value="DEBUG"/>
  </category>

  <category name="krasa.formatter">
    <priority value="DEBUG"/>
  </category>

  <root>
   <priority value="DEBUG"/>
   <appender-ref ref="DIALOG"/>
   <appender-ref ref="CONSOLE-WARN"/>
   <appender-ref ref="FILE"/>
 </root>
</log4j:configuration>
```

but honestly I dont get any debug logs (here the filtered logs):

`log.split('\n').filter(x => x.includes('formatter') || x.includes('krasa'))`:

```log
2021-06-14 17:34:02,798 [   9613]   INFO - ugin.ProjectCodeStyleInstaller - Overriding com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl with krasa.formatter.plugin.EclipseCodeStyleManager_IJ_2016_3plus' for project 'CENSORED' using CGLIB proxy 
2021-06-14 17:34:21,108 [  27923]   INFO - formatter.eclipse.Classloaders - Creating classloader for [file:/C:/Users/rxhaferi/AppData/Roaming/JetBrains/IntelliJIdea2021.1/plugins/EclipseFormatter/lib/adapter.jar, file:/C:/Users/rxhaferi/AppData/Roaming/JetBrains/IntelliJIdea2021.1/plugins/EclipseFormatter/lib/eclipse.jar] 
```

**Comment by krasa** [comment]
This is the way: 
![image](https://user-images.githubusercontent.com/1160875/121935640-f2379380-cd48-11eb-91d3-de3aa238bff6.png)
