### ISSUE TITLE
Eclipse Public License violations

### ISSUE THREAD

**Issue by howlger** [krasa/EclipseCodeFormatter#230]
This project **seems to violate** the [**Eclipse Public License (EPL)**](https://www.eclipse.org/legal/epl-2.0/), as it contains code released under the EPL without containing the license, and falsely claims that the entire project is released under the [Apache-2.0 License](https://github.com/krasa/EclipseCodeFormatter/blob/4aecb47d07c83f35933667abb3afe3f3feb2d446/LICENSE.txt):

- [`lib/eclipse/eclipse.jar`](https://github.com/krasa/EclipseCodeFormatter/blob/4aecb47d07c83f35933667abb3afe3f3feb2d446/lib/eclipse/eclipse.jar) seems to be repacked Eclipse platform and Eclipse JDT plugin JARs without any licenses and the `about.html` files removed.
- In GitHub, the project license is incorrectly stated as [Apache-2.0 License](https://github.com/krasa/EclipseCodeFormatter/blob/4aecb47d07c83f35933667abb3afe3f3feb2d446/LICENSE.txt)
- [In the JetBrains Marketplace](https://plugins.jetbrains.com/plugin/6546), the project license is incorrectly stated as  [Apache-2.0 License](https://github.com/krasa/EclipseCodeFormatter/blob/4aecb47d07c83f35933667abb3afe3f3feb2d446/LICENSE.txt)
- Also the [download](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=130185) does not seem to include an EPL file, nor does it seem to mention or tell the user about the EPL, although more than 85% of the code seems to be EPL

In addition, the **project name** starting with _Eclipse_ **violates** the [**Eclipse Foundation Trademark Usage Policy**](https://www.eclipse.org/legal/logo_guidelines.php):

> 6. You may not incorporate the name of an Eclipse Project Trademark into the name of your company or software product name. If you have a software product that works with an Eclipse Project, you may only use the following phrases: '\<product name> for \<Eclipse project name>' or '\<product name>, \<Eclipse project name> Edition'.

**Comment by krasa** [comment]
Thanks for the info. It will be fixed asap.

**Comment by krasa** [comment]
Not sure if the repository name needs to be changed. Other than that, all should be good now.

**Comment by heidelmeier-weclapp** [comment]
Does this mean, the plugin will only work with a local Eclipse installation? The update to 21.0 just broke my setup.

**Comment by krasa** [comment]
yes

**Comment by heidelmeier-weclapp** [comment]
I installed Eclipse 2021-09 and set the installation directory in the IntelliJ settings of this plugin. Doesn' work yet, I'm getting this exception: https://gist.github.com/heidelmeier-weclapp/eeb2381669868503fb4fad527d29e088

**Comment by howlger** [comment]
To be clear, EPL allows the use in both, open source and commercial products. Eclipse publishes the JARs on Maven Central making it easy to consume them also in non Eclipse based applications.

But like other licenses, EPL does not allow to remove or replace the licenses with another license, independent of whether the other license is compatible with the EPL or not.

**Comment by krasa** [comment]
@heidelmeier-weclapp Thanks, I removed too much. It should work now.

**Comment by markiewb** [comment]
First (not last): Thank you @krasa for your hard work and the ongoing maintenance of this plugin.

But removing the bundled eclipse-jars and rely on an external eclipse distribution is IMO inferior. I have to download an >100 MB distribution only for a formatter and to setup a path?

My proposal: Externalise the eclipse-jars into a separate plugin with EPL license and publish it to the IDEA marketplace. Your Code Formatter for Eclipse has a dependency to that plugin. When installing your plugin within the plugin dialog, IDEA should propose that other plugin automatically. Thus you can keep your plugin Apache 2.0-licensed and users can still rely on bundled eclipse-dependencies. Please reconsider this idea.

(Background story: This approach had been used by Apache NetBeans when they got OSS. The JDK/JVM-compiler-part for JDK8 has not been open-sourced/relicensed by Oracle. Thus Apache NetBeans asks you before using Java development to install the still-Oracle-licensed JDK/JVM-compiler-part as a plugin.)

**Comment by oesolutions** [comment]
If the long term solution is to continue requiring a local installation of Eclipse, please split the path settings into a separate configuration file so that this per-instance data can be excluded from version control.

**Comment by krasa** [comment]
@markiewb Thanks, you are right, it sucks, but I do not have time or energy to deal with it properly right now. 
The bundled lib was outdated all the time anyway, and I am glad I do not have to update it anymore, I'd rather spend time fixing bugs.

@oesolutions done, let's hope no one needs two locations.

**Comment by howlger** [comment]
To my understanding, this project **just wraps the Java formatter of the Eclipse JDT** project as an IntelliJ IDEA plugin. It is not the Eclipse Java coder formatter itself, as the former name implied, but is built on the Eclipse Java formatter. I would expect **this information with a link to Eclipse JDT project** and **which license applies to which part of the code** in the project description in both, in the README of the repository and in the marketplace entry.

I have reported this issue because that was not the case and even worse, **all references to the license have been removed from the Eclipse code**. To my understanding, this violates the EPL. Taking code from others, not telling doing so and removing the license doesn't seem fair to me. I don't know if the donations and the money from sponsors were kept, even though most of the work was and is done in Eclipse JDT.

In contrast to what @markiewb says, **EPL code** does not only allow, but **is intended to be used** (no separate plugins or repositories are required for this):
- EPL explicitly also allows the [_commercial distribution_](https://www.eclipse.org/legal/epl-2.0/#commercial-distribution) (in contrast to e.g. GPL)
- Typically there are non-UI plugins or separate _J(ava)_ projects (e.g. **J**Git vs. EGit or LSP4**J** vs. LSP4E) to be used in a plain Java application instead of in the Eclipse IDE or in an OSGi container
- Documented public API (do not use stuff of internal packages) and migration guides for the [platform](https://help.eclipse.org/latest/nav/2_3) and [JDT](https://help.eclipse.org/latest/nav/3_2)
- Eclipse plugin JARs are provided from eclipse.org and via Maven Central

**Comment by krasa** [comment]
I do not think the name implied anything like that. It was always clear that is an IntelliJ plugin. Also, the description stated that it `Allows using Eclipse's code formatter directly from IntelliJ`. It is literally the first thing in the project description.
It is not built on the Eclipse Java formatter, it only uses it. 

about.html was removed as a part of reducing the plugin size, it did not seem necessary.

It is not like I took the code and claimed it to be mine. Sure, there were formal mistakes, but nothing deceitful or malicious. I am no licensing expert and when any license issue came up in any of my project, it was quickly fixed. This one was missed for 10+ years. And talking about the chump change I received seems pretty rude to me. Maybe you are not familiar with these things, but there is absolutely no profit to be made by this or any other free plugin, if anything it is a total waste of time, a lot of time. There was zero time invested in this plugin by Eclipse folks, the same as any other third-party library that is used.

**Comment by howlger** [comment]
> There was zero time invested in this plugin by Eclipse folks

Your _Eclipse Code Formatter_ (not to be confused with the code formatter by Eclipse) was made up by 30 times more code by the Eclipse folks than by your glue code (not including the license notes you removed).

**Comment by krasa** [comment]
I think we are done here.

**Comment by RohanHart** [comment]
Given that other non-EPL projects such as SonarSource's sonar-java have a direct dependency on Eclipse's libraries can't that be an alternative rather than trying to depend on another plugin which depends on these libraries.
See https://github.com/SonarSource/sonar-java/blob/4b4ad5d011965e30af9a0558d2a50e8cdbadfb23/jdt/pom.xml

**Comment by howlger** [comment]
@RohanHart The problem was that Eclipse code was repackaged as [`eclipse.jar`](https://github.com/krasa/EclipseCodeFormatter/blob/4aecb47d07c83f35933667abb3afe3f3feb2d446/lib/eclipse/eclipse.jar) with all references to the EPL removed. In this Git repository as well as in the Marketplace entry it was falsely claimed that all the code is licensed under the Apache License 2.0. [As already explained, EPL code is intended to be used](https://github.com/krasa/EclipseCodeFormatter/issues/230#issuecomment-961883331). @krasa has decided to remove all EPL code rather than tell that it is EPL code.

**Comment by LumnitzF** [comment]
@krasa Would you be willing to accept a Pull request, which re-introduces the eclipse library with correct licence handling?

**Comment by krasa** [comment]
@LumnitzF I did not expect that people would hate installing Eclipse so much, so although the damage is already done, perhaps it would be good to add it back. 
So the answer is yes, but with some automated updater (https://github.com/krasa/EclipseCodeFormatter/tree/master/support) - afaik `plugin.xml` needs to get removed from the jars, IntelliJ does not like it.
