### ISSUE TITLE
Cannot be used without Eclipse installed

### ISSUE THREAD

**Issue by iruFu** [krasa/EclipseCodeFormatter#232]
> What steps will reproduce the issue?
Updating the verison to 21.0.203.000.1 in IntelliJ IDEA.

> What is the expected result?
Use the EclipseCodeFormatter plugin normally as usual (without Eclipse installed).

> What happens instead?
Error occurs when using the plugin with message 'Please set Eclipse installation location'.

> Paste information about IDE and OS (it can be copied from Help | About dialog).
IntelliJ IDEA 2021.2.3 (Community Edition)
Build #IC-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

**Comment by krasa** [comment]
yes, you need to install Eclipse.

**Comment by hanzhuofan** [comment]
> 是的，您需要安装 Eclipse。

why

**Comment by hanzhuofan** [comment]
> yes, you need to install Eclipse.

https://github.com/krasa/EclipseCodeFormatter/issues/230

**Comment by iruFu** [comment]
> yes, you need to install Eclipse.

Is it the new change in the latest verison with a requirement of compulsory Eclipse installed?
Cause it can be used without Ecilpse previously.

**Comment by iruFu** [comment]
> yes, you need to install Eclipse.

Just saw Issue#230, thanks.

**Comment by howlger** [comment]
@iruFu You misread issue #230. Including Eclipse is doable. @krasa chose the option of removing all the Eclipse code. But it would be also an option to stop removing the licenses from the Eclipse code and starting telling what is included from which project of which license.

**Comment by iruFu** [comment]
got it, appreciate
