### ISSUE TITLE
Plugin is forcing me to download eclipse

### ISSUE THREAD

**Issue by lkokot** [krasa/EclipseCodeFormatter#233]
> What is the expected result?
To work without forcing me to download eclipse as it used to work.

> What happens instead?
![image](https://user-images.githubusercontent.com/21138839/140689863-8ddeacc5-78c5-4573-9236-d57871f93ca0.png)

> Paste information about IDE and OS (it can be copied from Help | About dialog).
![image](https://user-images.githubusercontent.com/21138839/140689920-39aaf706-c1c2-4449-a7cc-db25bfa20ae3.png)
![image](https://user-images.githubusercontent.com/21138839/140689969-aa73bf28-81ee-4749-bd9b-736fbffd505f.png)

**Comment by caodangtinh** [comment]
This happend with new version, you have to specify eclipse installation folder. Don't know why we need this!

**Comment by Jacksonary** [comment]
same withe you after upgrade😥

**Comment by Nico-DF** [comment]
As always, please try to check existing (past) issues before opening new one. You can get your info from this issue: #230 

Long story short, there was some reclamation mades concerning the use of eclipse's jar in this plugin (license, name, etc.), and to cut the problem short, the main maintener has decided to rely on an external install of Eclipse to move the problem away (which is understable even though it might be a pain for end users)
