### ISSUE TITLE
Plugin requires whole eclipse workspace folder

### ISSUE THREAD

**Issue by maciejmiklas** [krasa/EclipseCodeFormatter#234]
Until now it was possible to provide only xml configuration in "Eclipse formatter config" -> "Eclipse workpsace/project folder or config file" 

Not when providing config file plugin will recognise profile from it, so it can parse given configuration. However clicking on Apply causes error: Cannot Save Settings: Path to 'Eclipse installation folder" is not valid.

<img width="1296" alt="ecf" src="https://user-images.githubusercontent.com/3326660/140733522-da15f7c8-e6b8-4f4f-97e8-52f8cb84d84e.png">

We are using this plugin only to have some eclipse functionality in IntellJ, like formatting. I do not have and will not have whole eclipse installation on my computer. 

This is new issue and makes this plugin in my case useless.

**Comment by gradlifier** [comment]
Ran into the exact same problem last Friday. Fortunately I am having an existing eclipse folder on that machine.

**Comment by renoth** [comment]
Version 21.0 removes the bundled eclipse libraries. @krasa is there a reason for that? It was very convenient to just supply the xml file and be done with the configuration and not be dependent on a local eclipse installation.

**Comment by krasa** [comment]
https://github.com/krasa/EclipseCodeFormatter/issues/233#issuecomment-962888493

**Comment by live52000** [comment]
> [#233 (comment)](https://github.com/krasa/EclipseCodeFormatter/issues/233#issuecomment-962888493)

Thanks for upgrade, but it seems not work on mac OS, when i config installation folder by "/Users/xxx/Eclipse.app".
Any correct guidelines for new version which can run on mac OS?

**Comment by krasa** [comment]
What does it say?

Please enable debug log  (Help | Diagnostic Tools | Debug Log...) for :
```
#krasa.formatter
krasa.formatter
``` 


You can downgrade https://plugins.jetbrains.com/plugin/6546-adapter-for-eclipse-code-formatter/versions/stable/130185

**Comment by live52000** [comment]
> Thanks for upgrade, but it seems not work on mac OS, when i config installation folder by "/Users/xxx/Eclipse.app".

now i know, config folder like "/Users/xxx/Eclipse.app/Contents/Eclipse" works.

**Comment by mhddurrah** [comment]
Yes, I guess we need to find an alternative unfortunately. downloaded 300 MB for an extension of size 100kb :)
even configuration became harder

**Comment by krasa** [comment]
Feel free to make one.

**Comment by krasa** [comment]
Fixed by https://github.com/krasa/EclipseCodeFormatter/pull/237
