### ISSUE TITLE
Allow eclipse location as project and global setting

### ISSUE THREAD

**Issue by LumnitzF** [krasa/EclipseCodeFormatter#236]
Background:
As far as I can see, the plugin depends on `org.eclipse.jdt.core` (including transitive dependencies). 
In order to keep the formatting of all our developers in sync, we would like to download this dependency in an initialization step and set up the formatter plugin to use it. 
With version 21.1 the setting for the eclipse location changed to a global setting, so we cannot set it per project anymore.

Goal:
Allow the eclipse location to be set as global setting and as project setting. If the project setting is configured, it overrides the global setting.

**Comment by jmiserez** [comment]
Do you still need this now that https://github.com/krasa/EclipseCodeFormatter/pull/237 is merged?

**Comment by LumnitzF** [comment]
No, as the eclipse library is now bundled again, I have no need for this anymore.
