### ISSUE TITLE
plugin incompatible

### ISSUE THREAD

**Issue by wzzjdsl** [krasa/EclipseCodeFormatter#238]
IDEA's browse repositories cannot search for the plugin. And install plugin from disk error：plugin is incompatible with this installation

![image](https://user-images.githubusercontent.com/5755833/143233706-1d95989d-086d-450c-b3e4-3c32106942bf.png)

![image](https://user-images.githubusercontent.com/5755833/143234219-d3df97ce-86e3-4ae7-9c53-a42f26b3df21.png)

**Comment by krasa** [comment]
try it now
