### ISSUE TITLE
@formatter:off is not working

### ISSUE THREAD

**Issue by emagin-es** [krasa/EclipseCodeFormatter#257]
> What steps will reproduce the issue?

- Install `IntelliJ IDEA 2023.1.3 (Community Edition)` 
- Install plugin EclipseCodeFormatter
- Navigate to Preferences → Adapter for Eclipse Code Formatter
    - Select "Use Eclipse’s Code Formatter"
    - Browse for Eclipse formatter config file: 
[gradle/eclipse-settings/common/org.eclipse.jdt.core.prefs](https://github.com/krasa/EclipseCodeFormatter/files/11925613/org.eclipse.jdt.core.prefs.zip)
- Navigate to Preferences → Editor → Code style
    - Activate `Turn formatter on/off with markers in code comments`

I tried adding `org.eclipse.jdt.core.formatter.use_on_off_tags=true` to the file `org.eclipse.jdt.core.prefs` as you mentioned in https://github.com/krasa/EclipseCodeFormatter/issues/64
I also tried disabling the plugin to be sure it is not an IntelliJ problem. Installing manually the previous version 22.0.203.000.0-Eclipse_2021-09 is not working, probably it is due to some IntelliJ change that broke the compatibility.
Some months ago it was working.

    

> What is the expected result?

Keep current code format.

> What happens instead?

Code is reformatted.

> Сonsider attaching a screenshot, screencast, or a code sample when it's hard to articulate the problem.
```
// @formatter:off
result
     .append(getBaseUrl())
     .append(PATH_PREFIX)
     .append("/")
     .append(id)
// @formatter:on
```

> Paste information about IDE and OS (it can be copied from Help | About dialog).

`IntelliJ IDEA 2023.1.3 (Community Edition)` 
`macOS 13.4.1 (22F82)`

**Comment by markiewb** [comment]
Try to remove the whitespaces.

***@***.***:off

instead of

// @formatter:off

Also for the on-tag

**Comment by emagin-es** [comment]
Sorry, I don't get what you mean with `***@***.***:off` (if I try to put it in the IntelliJ settings, it complains). 
I tried with and without whitespaces and the result is the same, without the plugin the formatter keeps the format, but with the plugin the block is formatted.

**Comment by emagin-es** [comment]
The problem is in the file `org.eclipse.jdt.core.prefs`, it contains `\\` when it should contains `\`.
![image](https://github.com/krasa/EclipseCodeFormatter/assets/34460662/8dcfab9f-0eb0-4269-8d14-f5eebb568331)
![image](https://github.com/krasa/EclipseCodeFormatter/assets/34460662/738d9ac5-8ad4-4695-aea4-783572633295)
This solves the problem.
