### ISSUE TITLE
Absolute Path to config file gets replaced with relative path using variable $PROJECT_DIR$ rendering settings unusable for a global central settings location

### ISSUE THREAD

**Issue by stefan-meissner** [krasa/EclipseCodeFormatter#258]
![image](https://github.com/krasa/EclipseCodeFormatter/assets/139456860/d114ce07-e695-47e0-8eae-3e535353154e)

Lets say we have a repository named "ProjectA" and we are pointing the path to the configuration file to a central location (e.g. `C:/Temp/settings/formatter/eclipse-formatter.xml`) it will be persisted in the project configuration file `eclipseCodeFormatter.xml` using `$PROJECT_DIR$` path variables resulting into this:

**ProjectA is located at C:\dev\myrepos\projects\ProjectA**
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="EclipseCodeFormatterProjectSettings">
    <option name="projectSpecificProfile">
      <ProjectSpecificProfile>
        <option name="formatter" value="ECLIPSE" />
        <option name="importOrderConfigFilePath" value="$PROJECT_DIR$/../../../../Temp/settings/formatter/eclipse.importorder" />
        <option name="importOrderFromFile" value="true" />
        <option name="pathToConfigFileJava" value="$PROJECT_DIR$/../../../../Temp/settings/formatter/eclipse-formatter.xml" />
        <option name="selectedJavaProfile" value="eclipse-formatter" />
      </ProjectSpecificProfile>
    </option>
  </component>
</project>
```

**ProjectA is located at C:\dev\ProjectA**
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="EclipseCodeFormatterProjectSettings">
    <option name="projectSpecificProfile">
      <ProjectSpecificProfile>
        <option name="formatter" value="ECLIPSE" />
        <option name="importOrderConfigFilePath" value="$PROJECT_DIR$/../../Temp/settings/formatter/eclipse.importorder" />
        <option name="importOrderFromFile" value="true" />
        <option name="pathToConfigFileJava" value="$PROJECT_DIR$/../../Temp/settings/formatter/eclipse-formatter.xml" />
        <option name="selectedJavaProfile" value="eclipse-formatter" />
      </ProjectSpecificProfile>
    </option>
  </component>
</project>
```

So if we want to use a centralized location for the config files and point to it (e.g. in multiple repos) and we have team members cloning projects in different locations, we will get changes everytime the plugin sets/resolves the path. When using a **global profile** it will be automatically set to the correct location (absolute path in global configuration file) but still using the path variable `$PROJECT_DIR$` for the project configuration file.

So either way the file will change all the time and we won't be able to share the configuration via git unless everyone is cloning into the same folder structure.

What would a workaround be? Is this behavior configurable?

**Comment by stefan-meissner** [comment]
Thanks for your answer, already thought it would be something like that.

So there is no way to get around that without a workaround on your or our side?

Maybe we have to copy the settings into every repository then... or something like that. We wanted to be able to change one file centrally for a given profile in multiple projects.

**Comment by krasa** [comment]
You could clone your projects to a single workspace where the relative path would be always the same for everyone.

The problem is that the global profile saves itself to the project settings, which in your case produces changes. 
The only solution I can think of is to add a checkbox that would disable it so that only a profile id/name would be saved to the project config.

**Comment by krasa** [comment]
You may try it:

Uncheck this:
![image](https://github.com/krasa/EclipseCodeFormatter/assets/1160875/549aee37-6054-44f1-b5ae-a223a369690f)

[EclipseFormatter-23.2.223.000.0-Eclipse_2023-03.zip](https://github.com/krasa/EclipseCodeFormatter/files/12104402/EclipseFormatter-23.2.223.000.0-Eclipse_2023-03.zip)

**Comment by stefan-meissner** [comment]
Looks good and works fine.

Thank you for your fast response and this fix, nice work!

**Comment by krasa** [comment]
Thank you!
