### ISSUE TITLE
Upgrade bundled eclipse to 2023-12 (4.30)

### ISSUE THREAD

**Issue by jpraet** [krasa/EclipseCodeFormatter#263]
Could the bundled eclipse version be upgraded to 2023-12, in order to support the new language features introduced in JDK21?

https://eclipse.dev/eclipse/news/4.30/jdt.php#Java21

**Comment by rokkolesa** [comment]
This is a big problem if the code uses some preview features. It seems that using `2023-12` should fix that. We are also using `spotless-maven-plugin` to check the code on our CI/CD pipeline. When we specify the `2023-12` version in the maven plugin, the code is correctly checked.. but it completely fails to format the file using this plugin, where an older eclipse is bundled.

**Comment by krasa** [comment]
Yes, but using an external Eclipse installation should help.

**Comment by rokkolesa** [comment]
That is true, but we do not want to force every developer to install eclipse.

Regardless, the `2023-12` version does not fix formatting of the preview features - I was mistaken before.

Is formatting of the preview features even enabled in eclipse?

For example, take a look at this example code:
```java
try {
 process();
}
catch (Exception _)
{
   log.warn("Cannot process, but continuing anyway!");
}
```
As soon as this feature is used (the unnamed variable in the catch clause) somewhere in the class, the formatting fails completely. It does not format any lines.

**Comment by krasa** [comment]
new version should be approved in few days
