### ISSUE TITLE
IDEA 14 - JSP "organize imports" deletes imports

### ISSUE THREAD

**Issue by mschel** [krasa/EclipseCodeFormatter#32]
Hi there - the plugin behaves strange on JSP files.
With IDEA 14.0.2 and JSPs with import statements all imports will be deleted (by the plugin I guess) when running "organize imports" command.

When disabling the plugin it's working fine.
Could reproduce it on different machines (Win7) with different settings and no plugins installed expect yours.

Thanks for help :)

**Comment by krasa** [comment]
does eclipse even sort imports somehow? mine does nothing...

**Comment by eden91940** [comment]
+1

**Comment by krasa** [comment]
fixed
