### ISSUE TITLE
Imports optimized using IntellijFormatter instead of EclipseFormatter

### ISSUE THREAD

**Issue by jlupi** [krasa/EclipseCodeFormatter#36]
When I set the cursor over an unused import and execute Alt+Enter and select Optimize Imports, Intellij does that using the build-in formatter.

For example:

This is how my EclipseFormatter is configured (the code is formatted):

![image](https://cloud.githubusercontent.com/assets/4189968/6058879/febeef2a-ad2b-11e4-8df8-4b28e8e95804.png)

Now I put an unused import and do Alt+Enter -> Optimize Imports

![image](https://cloud.githubusercontent.com/assets/4189968/6058902/292bc8a0-ad2c-11e4-9947-06c073b9d79a.png)

The result is:

![image](https://cloud.githubusercontent.com/assets/4189968/6058910/3eaaa0ca-ad2c-11e4-90a9-11ed4614a847.png)

As you can see the imports are reordered (Intellij configuration is used)

**Comment by krasa** [comment]
That would have to be fixed in IntelliJ itself... I will see if I can do something about it.

**Comment by krasa** [comment]
Duplicated https://github.com/krasa/EclipseCodeFormatter/issues/109
