### ISSUE TITLE
License

### ISSUE THREAD

**Issue by youribonnaffe** [krasa/EclipseCodeFormatter#41]
Hi,

I was just wondering if any license was applied to this project. I took some pieces of code to add import ordering to my Gradle format plugin (https://github.com/youribonnaffe/gradle-format-plugin/issues/4) and I wondered if it would be ok to do so. It is mostly ImportsSorter and ImportSorterAdapter classes.

Thanks

**Comment by krasa** [comment]
Hi, take whatever you need. I pushed an Apache 2 license file.

**Comment by youribonnaffe** [comment]
Thanks
