### ISSUE TITLE
Allow to format Maven archetype prototype files

### ISSUE THREAD

**Issue by dschmucki** [krasa/EclipseCodeFormatter#42]
Formatting of prototype files does not work (Xyz.java failed to format with Eclipse code formatter. Probably due to syntax error or wrong configuration file.)

Prototype files usually start with a
`package ${package}.xyz;`
and use
`import ${package}.abc.Def;`
which seem to make some difficulties to the formatter.

It would be nice to have this feature, as I have to build archetypes from time to time and especially these should come with correct formatting.

**Comment by krasa** [comment]
well, eclipse itself cannot format it, the only way would be to replace those ${package} before formatting, and then replace it back.

**Comment by dschmucki** [comment]
Bummer! Thanks for the fast reply!
