### ISSUE TITLE
Unable to Configure

### ISSUE THREAD

**Issue by leandroferro** [krasa/EclipseCodeFormatter#43]
Hi!
I've just installed 14.8.132.637 in intelliJ 14.1.1 and I'm not able to configure. I've already restarted the IDE and I cannot find the Settings -> Other Settings option.
Do you know if there is any problem with these versions?

Thank you!

**Comment by krasa** [comment]
Is the plugin enabled? I have no such problems.

![image](https://cloud.githubusercontent.com/assets/1160875/7274908/012bf300-e901-11e4-9464-45ec2ad12184.png)

**Comment by leandroferro** [comment]
Yes, it was, but the configuration screen was only enabled after I imported/created a project. From the settings option of the splash screen of intellij I wasn't able to use it, but it's working.

Thank you!

**Comment by thecatwhisperer** [comment]
Why is this closed?  Not being able to configure this plugin until a project is created/imported is a bit... wrong?  I spent a while trying to figure out what was going on before I found this post.
