### ISSUE TITLE
Path to config file uses absolute pathing

### ISSUE THREAD

**Issue by linjer** [krasa/EclipseCodeFormatter#47]
When I select a config file under "Eclipse Java Formatter config file" it would be preferable for it to resolve into a relative path, relative to the project. On a team project where we try to keep our formatting synced up to avoid unnecessary edit wars, this would be convenient.

Also given your examples under the path text box, it looks like relative pathing is possible, but its very unclear where the reference point is. Making a few guessing as to where that is, I still cannot get it to find the file, even while trying variables like `$PROJECT_DIR$`.

**Comment by krasa** [comment]
Good point, the base dir seems to be Intellij's JRE bin folder.

**Comment by linjer** [comment]
Ah good to know. Trouble is checking in these settings for other team members to use, the IntelliJ JRE bin folder is still not consistent enough for people to set it and forget it. Would it be possible to add better support for relative pathing?

**Comment by krasa** [comment]
Sure. I just need to make sure to not break everyone's settings...

**Comment by krasa** [comment]
The thing is, it seems that the relative path is kinda automatic (#26), I configured 'F:/workspace/format.xml' as a path, and it was persisted into misc.xml as '$PROJECT_DIR$/../../../format.xml'

**Comment by linjer** [comment]
While digging around for some other stuff, I found this. Just as a note, I'm working in Mac OSX 10.10.3 with IntelliJ 14.1

```jerrylin:options/ $ cat eclipseCodeFormatter.xml                                                                                                 [17:06:25]
<application>
  <component name="EclipseCodeFormatterSettings">
    <option name="settingsList">
      <list>
        <Settings>
          <option name="defaultSettings" value="true" />
          <option name="formatter" value="ECLIPSE" />
          <option name="id" value="1434077873399" />
          <option name="importOrderConfigFilePath" value="$USER_HOME$/Desktop/redacted-style.importorder" />
          <option name="name" value="default" />
          <option name="pathToConfigFileJava" value="$USER_HOME$/Projects/redacted/project/eclipse_formatter.xml" />
          <option name="selectedJavaProfile" value="redacted" />
        </Settings>
      </list>
    </option>
  </component>
</application>%```

**Comment by krasa** [comment]
* eclipseCodeFormatter.xml is a global IDE config
* mixc.xml is a project config. You are commiting and conflicting on that, right? You might see something different there...

**Comment by linjer** [comment]
You are right. I am seeing this in misc.xml:

```xml
<component name="EclipseCodeFormatter">
    <option name="defaultSettings" value="true" />
    <option name="formatter" value="ECLIPSE" />
    <option name="id" value="1434077873399" />
    <option name="importOrderConfigFilePath" value="$USER_HOME$/Desktop/connectifier-style.importorder" />
    <option name="name" value="default" />
    <option name="pathToConfigFileJava" value="$PROJECT_DIR$/project/eclipse_formatter.xml" />
    <option name="selectedJavaProfile" value="Connectifier" />
  </component>
```

**Comment by krasa** [comment]
So everything is ok then? No need to do anything?
