### ISSUE TITLE
Add support for Eclipse CDT code style formatter

### ISSUE THREAD

**Issue by weitjong** [krasa/EclipseCodeFormatter#49]
This plugin has potential. It has been registered as available for CLion users as well. However, after installing it in CLion, it appears it only supports Java/JavaScript code style formatter. It would be great if the C/C++ code style formatter is being supported as well. Thanks.

**Comment by krasa** [comment]
Seems possible.

**Comment by krasa** [comment]
Done. You can try it from here: https://github.com/krasa/EclipseCodeFormatter/releases/tag/cdt

**Comment by weitjong** [comment]
Thanks. That's fast! I will try it when I have time later. But before I do that, I have one question. I have spent some time yesterday to setup the built-in code style formatting in CLion to match what I used to have in my Eclipse setup, thinking that this issue won't get fix this fast :smiley:. It is close to but not quite there yet. So, if I reinstall this plugin in CLion and set it up to use my Eclipse exported code style formatter then will the plugin supplements the built-in formatter? Or it simply suppresses the built-in one? How does it work internally?

**Comment by krasa** [comment]
The Eclipse formatter is used only in some situations, so having a similar settings for IntelliJ formatter is very beneficial. I use an IntelliJ API with ~20 methods, some things are delegated to the original IntelliJ formatter, some are implemented in the plugin, Eclipse formatter API has 1 method for formatting a plain string, so a lot of things which IntelliJ does is not that easy with Eclipse...

For example Live templates formatting uses Intellij formatter by defualt - using Eclipse can cause that a next step in live template will have a wrong selection...
Or ctrl+shift+enter indents a line using IntelliJ formatter.

Generally Eclipse formatter is used when you trigger formatting manually, for selection or the whole file/package, and formatting before commit.  
Perhaps the support could be improved for some cases, but there was no real need...

**Comment by weitjong** [comment]
Thanks for your answer but I am still a bit lost. I think I understand the part that you need to use IntelliJ API to implement the formatting and that it is not a one-to-one mapping with Eclipse settings. My question is more about which formatter has the precedence. Let's put aside other formatting situation first and just focus on the manual formatting use case. Say, when I am using Ctrl+Alt+L to format a C/C++ source file or header file, does the IntelliJ formatter does it work first then follows by your plugin? Or only your plugin does the formatting work (suppressing IntelliJ)?

**Comment by krasa** [comment]
Only my plugin does the work (suppressing IntelliJ).

**Comment by weitjong** [comment]
Thanks for patient in answering my question. I have time to try the new tag. It installs successfully just like last time. The settings now have option for C/C++ formatter config file. However, after specifying the path to my Eclipse exported settings file, there is nothing being listed in the formatter profile drop down list as expected. If I use the same step but in the Java formatter config file then my exported profile is listed under the Java formatter profile. So, something must have goes wrong. I could not test further after this point.

**Comment by krasa** [comment]
Sorry, copy paste error. Fixed: https://github.com/krasa/EclipseCodeFormatter/releases/tag/cdt2

**Comment by weitjong** [comment]
Thank for the quick fix again. The new tag works as expected this time. Kudos.

**Comment by weitjong** [comment]
BTW, there is one small cosmetic issue. Your setting form is not scrollable using mouse wheel unlike the rest of the settings form in he CLion. Only when my mouse pointer is on top the vertical bar then the mouse wheel functions.

**Comment by krasa** [comment]
Good catch, thanks.
