### ISSUE TITLE
Cursor jumps after formatting

### ISSUE THREAD

**Issue by ruisalgado** [krasa/EclipseCodeFormatter#53]
As exemplified here:

![eclipsecodeformattercursorissue](https://cloud.githubusercontent.com/assets/234036/8854842/f533f09c-3159-11e5-91cf-bb761feefd99.gif)

It becomes incredibly annoying when you have autosave triggering the formatting. 

Any idea what could be causing this?

I'm on Intellij Idea `14.1.4`, Eclipse Code Formatter plugin version `15.1.132.637.0`

Here's my [formatter config file](https://gist.github.com/ruisalgado/c1dcedfa93cba36a5f09)

**Comment by krasa** [comment]
Try to import the Eclispe code style file into IntelliJ (File | Settings | Editor | Code Style | Manage...), some things might be caused by using spaces in IntelliJ code style and tabs in Eclipse code style.

**Comment by ruisalgado** [comment]
@krasa that didn't help. I also commented out all the settings in the formatter xml and still saw the same behaviour, even though the plugin complained about not being able to load the profile:

```
12:31:42 Thing.java failed to format with Eclipse code formatter. loading of profile settings failed, profile has no settings elements         
12:31:44 Thing.java formatted successfully by Eclipse code formatter
```

**Comment by krasa** [comment]
I think I have the fix, could you try it? https://github.com/krasa/EclipseCodeFormatter/releases/download/15.2.132.637.0/EclipseFormatter.zip

**Comment by ruisalgado** [comment]
Just tested it and seems to be working fine! Nice work!

**Comment by krasa** [comment]
Thanks.
