### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by frunk** [krasa/EclipseCodeFormatter#58]
The following code:

    public void foo() {
		if (true) {
			if (true) {
				if (true) {
					if (true) {
						if (true) {

						}
					}
				}
			}
		}
	}
is getting formatted with indentation fault:

    public void foo() {
		if (true) {
			if (true) {
			if (true) {
				if (true) {
					if (true) {

					}
				}
			}
			}
		}
	}

The problem only occurs when using version 4.5 of EclipseCodeFormatter. When using 4.4, the indentation is correct.

**Comment by krasa** [comment]
Works fine for me, probably due to different config. 
Have you tried it in Eclipse 4.5 itself? Looks like a bug from there
, nothing I can do about it.

**Comment by frunk** [comment]
I see. I only tried with Eclipse 4.4.
So I should export format-settings from Eclipse 4.5 to get it working in the EclipseCodeFormatter-IntellijPlugin with mode "Version 4.5", right? Did not know, that format of the export.xml has been changed in Eclipse 4.5 and is not compatible to 4.4.

**Comment by krasa** [comment]
export.xml should be compatible, maybe some option behaves differently.
