### ISSUE TITLE
Invalid indentation

### ISSUE THREAD

**Issue by akornev** [krasa/EclipseCodeFormatter#60]
Please see attached screenshot. It started happening after one of the recent updates of the Formatter plugin. The method declaration gets indented twice unless either the method is qualified as `public`, or the `Use Eclipse 4.4 Java formatter` check box in Settings is checked.
![snip](https://cloud.githubusercontent.com/assets/1650235/9152556/8cb7023a-3de2-11e5-8350-e603bc7bd4bc.PNG)

**Comment by krasa** [comment]
Is it happening also in Eclipse 4.5 with your settings file? Could you attach it?

**Comment by akornev** [comment]
Yes, the same thing happens in Mars. In fact, the Line Wrapping setting for Method Declaration was the culprit: setting it to "Wrap where necessary" causes the above issue, and reverting it back to "Do not wrap" makes the formatting look ok again. 

I'm guessing this issue is related to Eclipse rather than the plugin?

**Comment by krasa** [comment]
Yep.
