### ISSUE TITLE
Formatter line wrap imprecision

### ISSUE THREAD

**Issue by jsimsa** [krasa/EclipseCodeFormatter#62]
My config file specifies uses 100 as a value to split lines: <setting id="org.eclipse.jdt.core.formatter.lineSplit" value="100"/>

However, in some cases the formatter produces output that contains lines with more than 100 characters. For instance:

```
public class RPCBlockWriteRequest extends RPCRequest {
  private final long mUserId;
  private final long mBlockId;
  private final long mOffset;
  private final long mLength;
  private final DataBuffer mData;

  public RPCBlockWriteRequest(long userId, long blockId, long offset, long length, DataBuffer data) {
    mUserId = userId;
    mBlockId = blockId;
    mOffset = offset;
    mLength = length;
    mData = data;
  }
}
```

The constructor method is 101 characters long and the formatter does not wrap it.

I tried playing with the value of the line split and indentation and it seems that the formatter treats each level of indentation as a single space (as opposed to however many spaces there are).

Is this something that can be fixed in the formatter itself? Or is there another property in the config I could set to resolve this? Any help would be appreciated. Thanks.

**Comment by jsimsa** [comment]
@calvinjia

**Comment by krasa** [comment]
Have you tried it in Eclipse itself?

**Comment by jsimsa** [comment]
Just tried this with a newly installed Eclipse 4.5. Setting the maximum line width to 100, indentation policy to "spaces only" and indentation size and tab size to 2. It wraps the lines properly.

**Comment by krasa** [comment]
I just tried it in Eclipse 4.5.2, and it behaves exactly like with the plugin. I would need to have your config file....
