### ISSUE TITLE
Javadoc in java files are ignored when formatting

### ISSUE THREAD

**Issue by Macadoshis** [krasa/EclipseCodeFormatter#68]
Multiline Javadoc ("/** ... */") in java files are ignored when formatting.

Java code around javadoc is formatted successfully, but not the javacode. Comments ("// ..." and "/* ... */") and singleline javadoc ("/** ... */") are formatted successfully too.

Example :
```
/**
         * Multi-line Javadoc
                       */
           List<String>          save1   (      Object    obj);

        /** Single-line Save */
    List     <String>    save2   (Object    obj     );

   /**
         * Multi-line Comment
                       */
```
becomes : 
```
/**
         * Multi-line Javadoc
                       */
List<String> save1(Object obj);

/** Single-line Save */
List<String> save2(Object obj);

   /**
         * Multi-line Comment
                       */
```

Expected :
```
/**
  * Multi-line Javadoc
  */
List<String> save1(Object obj);

/** Single-line Save */
List<String> save2(Object obj);

/**
 * Multi-line Comment
 */
```

**Comment by krasa** [comment]
works fine for me

**Comment by Macadoshis** [comment]
What kind of sorcery is this ?

Please have a try with my Eclipse files : http://filebin.net/03l1xcfa8c

![image](https://cloud.githubusercontent.com/assets/2878861/9932649/e6b0b1d2-5d45-11e5-9cbd-4d6af5778dc8.png)
![image](https://cloud.githubusercontent.com/assets/2878861/9932679/11732ed6-5d46-11e5-90dc-89c99a52ba63.png)

**Comment by krasa** [comment]
org.eclipse.jdt.core.prefs:
```
org.eclipse.jdt.core.formatter.comment.format_block_comments=false
org.eclipse.jdt.core.formatter.comment.format_javadoc_comments=false
org.eclipse.jdt.core.formatter.comment.format_line_comments=false
```

that's it, but the file is too short anyways, please go through https://github.com/krasa/EclipseCodeFormatter/blob/master/README.markdown#instructions - on "Get Eclipse formatter settings file"

**Comment by Macadoshis** [comment]
You the man ! thanks a lot.
My bad, turns out it's a *RTFM* issue :)
