### ISSUE TITLE
scalariform formatting

### ISSUE THREAD

**Issue by jozic** [krasa/EclipseCodeFormatter#70]
Hey, sorry for the issue, but i didn't find a mailing list or gitter link, so here is this issue.

This plugin seems to me more than just eclipse formatter, it's an alternative formatter which right now supports only eclipse formats. 
I'm interested in having a way to format scala code using scalariform library, but with standard intellij way. And looks like your plugin is doing exactly same thing.
It's probably possible to fork this repo and replace eclipse formatter with scalariform. But one probably won't be able to use both plugins at same time. So i'm more interested in combining different formatters in your plugin.
Do you consider adding support for other formatting libs? I can contribute scalariform formatting if so.

Feel free to move this to a mailing list/gitter channel if you have one.

**Comment by krasa** [comment]
Hi, this place is fine.

You are right that there can be only one plugin at the same time, but we could perhaps do something about it. Maybe introduce some new API into IntelliJ, or make a small plugin for registering formatters on which we could have a dependency. This plugin is hooked in a very bad way, but nothing else was possible.

I could combine more formatters, but there are several problems
- the plugin is already too big from all those Eclipse jars 
  - I probably need a lazy downloading of jars, that could even help me to remove all that reflection handling pain of class conflicts. Or split the plugin on Core, and optional plugins which would contain specific formatter jars + facade
- what should be the new name of the plugin? "Eclipse formatter and friends"? :-)
- I don't have much time and I don't even need to use this plugin anymore
- there are or will be other people which want to make their own plugin (https://github.com/google/google-java-format), so the new API could be a good idea anyways
