### ISSUE TITLE
Filed to format json with class as attribute name

### ISSUE THREAD

**Issue by SoftwareTipi** [krasa/EclipseCodeFormatter#71]
I've got error: "failed to format with Eclipse code formatter. Probably due to syntax error or wrong configuration file", when trying to format json with 'class' (without quotes) attribute eg:

``` javascript
var crachMe = {
    class: 'test'
}
```

Everything works fine for:

``` javascript
var crachMe = {
    'class': 'test'
}
```

**Comment by krasa** [comment]
This plugin does not format json files...

**Comment by Krzychek** [comment]
But objects in JS are initialized in json format and this plugin does format Javascript.. Anyway, both  provided snippets are fully legal Javascript code and first of them crash formatter, probably because class is reserved word (but could be used as property name on object as far as I know).

**Comment by krasa** [comment]
JS support was removed.
