### ISSUE TITLE
Update Mars formatter to 4.5.1 

### ISSUE THREAD

**Issue by u3r** [krasa/EclipseCodeFormatter#72]
Mars Service Release 1 fixes a LOT of bugs in the new eclipse formatter.
Current Formatter should be updated soon.

**Comment by krasa** [comment]
Thanks, will do.

**Comment by krasa** [comment]
You can try it, if you install the plugin manually: https://github.com/krasa/EclipseCodeFormatter/releases/download/15.3/EclipseFormatter.zip
