### ISSUE TITLE
Workspace Mechanic

### ISSUE THREAD

**Issue by eplatti** [krasa/EclipseCodeFormatter#73]
We use [Workspace Mechanic](https://code.google.com/a/eclipselabs.org/p/workspacemechanic) to setup our formatting rules in Eclipse. It would be very valuable to be able to use the same configuration files for both Eclipse and IntelliJ. 

The only difference is that the Mechanic file include preference scope and node:

```
/instance/org.eclipse.jdt.core/org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_package=insert
```

While this seems to be implied for the IntelliJ EclipseCodeFormatter:

```
org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_package=insert
```

Would it be possible to add support for both formats?

**Comment by krasa** [comment]
Sure, pull request welcomed.

**Comment by markiewb** [comment]
The relevant part in my plugin is https://github.com/markiewb/eclipsecodeformatter_for_netbeans/commit/3f9ee43e217a3115e310145263126b2af738555e#diff-db36cb29520e5f1c682bc21a711dbf90R146

**Comment by markiewb** [comment]
@krasa: Please review and merge the pull request https://github.com/krasa/EclipseCodeFormatter/pull/121

**Comment by markiewb** [comment]
Already merged via https://github.com/krasa/EclipseCodeFormatter/pull/121

@krasa: Please close this issue.
