### ISSUE TITLE
Wrong intendation of method name after JavaDoc

### ISSUE THREAD

**Issue by proshin-roman** [krasa/EclipseCodeFormatter#74]
Incorrect indentation in the next case:
```
    /**
     * Some comment here
     *
     * @param parameters
     *            parameter description
     */
            void methodName(String... parameters);
```
And the correct formatting should be next:
```
    /**
     * Some comment here
     *
     * @param parameters
     *            parameter description
     */
    void methodName(String... parameters);
````
Version of IntelliJ IDEA is: 14.1.5 (Build #IU-141.2735, built on September 22, 2015)
Version of Eclipse Code Formatter is: 15.2.132.637.2
JRE: 1.7.0_80-b15 amd64
It's a screenshot of configuration in IDEA: 
![eclipse-formatter-config](https://cloud.githubusercontent.com/assets/3031372/10638734/fcf4f928-7814-11e5-86c8-3e10b0a50ed4.png)

And with IntelliJ IDEA 13.x it worked correctly, so I guess that the problem might be related to an integration with IDEA. As well I can attach my configuration .xml file.

**Comment by krasa** [comment]
Have you tried to tick  "Use Eclipse 4.4 formatter"?

**Comment by proshin-roman** [comment]
Yeah, your advice about "Use Eclipse 4.4 formatter" fixed the issue! Thanks a lot!
