### ISSUE TITLE
Eclipse Code Formatter does not work in IntellijIdea 14.1.5 

### ISSUE THREAD

**Issue by arthurdn** [krasa/EclipseCodeFormatter#76]
I attached logs and screenshots, invalidate caches and restart did not helped.

![untitled](https://cloud.githubusercontent.com/assets/3274576/10973855/ed6f48bc-83e7-11e5-9a9e-00810e59d2e8.png)
![untitled-2](https://cloud.githubusercontent.com/assets/3274576/10973856/ed7054dc-83e7-11e5-8b8d-e02e32338e8f.png)

"JetBrains" support told me, that this is might me a plugin problem.
When "Eclipse Code Formatter" is enabled, formatting does not work, when it is disabled, adll works fine.
https://drive.google.com/file/d/0Bzt9nyplIr7OUEJCbnVZaEs0SzA/view?usp=sharing (log files).

**Comment by krasa** [comment]
try to reinstall the plugin, it seems you are missing a jar

**Comment by arthurdn** [comment]
Helped.
