### ISSUE TITLE
Do not support IntelliJ idea 15?

### ISSUE THREAD

**Issue by zhoudi** [krasa/EclipseCodeFormatter#77]
can not formate the java code accurately when run plugin.

**Comment by mkp05** [comment]
Turn off the plugin, restart IDEA and turn on the plugin again. After that plugins seems to work again.

**Comment by krasa** [comment]
That's strange... :(

**Comment by vehovmar** [comment]
I have similar problem in Intellij 15/16 EAP. Configuration tab "Settings | Other Settings | Eclipse Code Formatter" is not there anymore. Turning off/on the plugin didn't help. Any ideas?

**Comment by ivandariojr** [comment]
Same problem as vehovmar happening on Clion EAP build 144.3143.4. I cannot access the Other Settings Tab. Any workarounds?

**Comment by krasa** [comment]
Did you try to reinstall the plugin? Is there anything in the log? 
I will probably try it myself tommorow...

**Comment by ivandariojr** [comment]
Reinstalling had no effect. I do not see anything in the event log unless there is some other log I should check.

**Comment by vehovmar** [comment]
Reinstall didn't help me either.

**Comment by krasa** [comment]
Working on fix... they broke almost all my plugins :(

**Comment by krasa** [comment]
fixed, i will release it soon, testers welcomed :] https://github.com/krasa/EclipseCodeFormatter/releases/download/15.4.132.637.0/EclipseFormatter.zip

**Comment by vehovmar** [comment]
Works for me! Thanks!

**Comment by mdoninger** [comment]
Works also for me, thanks.

**Comment by ivandariojr** [comment]
The fix worked for me. Thanks!
