### ISSUE TITLE
eclipse formatter is not invoked during commit

### ISSUE THREAD

**Issue by vadimnyc** [krasa/EclipseCodeFormatter#79]
when you commit a file there are options: reformat code, reaarange code, optimize imports, update copyright. It looks like that default intelliJ formatter is used vs enabled eclipse formatter plugin

**Comment by krasa** [comment]
works fine for me, can you be more specific?

**Comment by vadimnyc** [comment]
actually apologies, must have been something specific at my work IntelliJ configuration environment. I just did exactly same setup @ home and it does work as expected! The only difference I can think of is that I use bitbucket&git @ home and svn @ work... but I doubt that version control matters for this case! 

thank you for an amazing plugin, I'll see if I can narrow it down at work to something more specific!

**Comment by markiewb** [comment]
@krasa: So you can close this issue.

**Comment by krasa** [comment]
@markiewb I can probably close a lot of issues :)
