### ISSUE TITLE
Wrapping in different places than Eclipse

### ISSUE THREAD

**Issue by bemace** [krasa/EclipseCodeFormatter#86]
I'm moving from Eclipse Luna (4.4.2) to IntelliJ 15.0.4 w/ Eclipse Formatter 15.4.132.637.0.

I've imported our formatter settings from an XML file exported from Eclipse. Everything seems to be working except certain cases of line wrapping. I've verified that both are using 120 char lines and 4-space indents. I've attached sample files as formatted by each. 

In the last method I noticed that Eclipse apparently makes a judgement call to go a couple characters past 120 rather than wrapping. For the others, I think IntelliJ is actually wrapping them in better locations, but I need to maintain consistency with Eclipse for now.

[Formatting Samples.zip](https://github.com/krasa/EclipseCodeFormatter/files/153048/Formatting.Samples.zip)

Also, a side-by-side diff with Eclipse on the left:
![formatting sample](https://cloud.githubusercontent.com/assets/546341/13432644/1f6507e6-df94-11e5-9469-05d484472a94.PNG)

**Comment by markiewb** [comment]
Have you tried to use the 4.4 engine?
![2016-03-01_21h10_20](https://cloud.githubusercontent.com/assets/1857095/13440386/0f99abf6-dff2-11e5-95b4-329f2674d824.png)

It has been introduced by #51 to switch between the 4.4 and 4.5 engine, because 4.5 is not fully backwards compatible

**Comment by bemace** [comment]
Nice, that took care of it. I was fixated on the JRE version requirement and didn't realize the formatter output changed as well.

**Comment by markiewb** [comment]
You are welcome.
