### ISSUE TITLE
Editor tab changes to blue when there's no changes after format

### ISSUE THREAD

**Issue by petria** [krasa/EclipseCodeFormatter#87]
Editor tab in IDEA changes to blue indicating file is changed after doing code format with EclipseCodeFormatter. How ever when you check with commit dialog (git) and show differences view, there is no differences between before / after formatting.

**Comment by krasa** [comment]
Does `Refresh VCS changes` button in Version Control tool window help?

**Comment by krasa** [comment]
Looks familiar?  
![image](https://cloud.githubusercontent.com/assets/1160875/13563310/fe7c30fc-e440-11e5-8bef-ec33062ba86b.png)

**Comment by krasa** [comment]
Hmm IJ 16 seem to have a problem with that, but after I edit another file, the project view changes it back to white...

**Comment by petria** [comment]
Yes sometimes later it usually goes back from blue ...

I have also setup git so it won't count CRLF as change...

**Comment by petria** [comment]
I am using IJ 15.0.3 Community edition ...

**Comment by krasa** [comment]
fixed, you can try it from here:
https://github.com/krasa/EclipseCodeFormatter/releases/download/15.5.132.637.0/EclipseFormatter.zip
