### ISSUE TITLE
URGENT QUESTION: Eclipse and Intellij Reformat do not match

### ISSUE THREAD

**Issue by victropolis** [krasa/EclipseCodeFormatter#90]
I reformatted our code base in eclipse and in intellij using Eclipse Code Formatter using the same eclipse format config file and the results do not match.  Should they?  Thanks!

**Comment by krasa** [comment]
They should match 100%, that's the point of the plugin. Whats your Eclipse version?

**Comment by victropolis** [comment]
Mars 4.5.2

**Comment by krasa** [comment]
Well, there might be some small differences since the plugin has jars from 4.5.1, but if it is anything big, you might have a bad config file...

**Comment by victropolis** [comment]
@krasa as a test, I took the following eclipse code style config from google and formatted our code in  eclipse, committed to version control, reverted those changes, formatted in intellij using Eclipse Code Formatter using the same config file, and the results didn't match.

**Comment by victropolis** [comment]
@krasa the differences seem to have to do mostly with line wrapping and combining lines that were already wrapped, from what I can see.

**Comment by krasa** [comment]
can you link the config?

**Comment by victropolis** [comment]
Sorry @krasa I thought I'd pasted the link.  Here it is:  https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml

**Comment by krasa** [comment]
Works fine for me, do you have any file as example?

**Comment by linjer** [comment]
I'm having the same issue between Eclipse 4.5.2 and the IntelliJ plugin. It looks like the import ordering was re-written recently (guessing from this ticket: https://bugs.eclipse.org/bugs/show_bug.cgi?id=430303). It seems rather consistently to put "all others" at the bottom now, whereas before it would put others between the defined groups.

**Comment by krasa** [comment]
done, you can try it from here:
https://github.com/krasa/EclipseCodeFormatter/releases/download/15.5.132.637.0/EclipseFormatter.zip
