### ISSUE TITLE
Can't find configuration menu in Android Studio 2.0

### ISSUE THREAD

**Issue by sebasguillen** [krasa/EclipseCodeFormatter#91]
The menu 'Settings > Other Settings' [is not there](http://stackoverflow.com/questions/36552963/where-did-the-other-settings-go-in-android-studio-2).
How can I configure the plugin?

**Comment by krasa** [comment]
Do you have a project opened?

**Comment by sebasguillen** [comment]
Other Settings doesn't show if a project is not opened. 
Thank you.
