### ISSUE TITLE
Missing 4.5.2 support

### ISSUE THREAD

**Issue by nicou50** [krasa/EclipseCodeFormatter#92]
Hi, 

Eclipse Mars 2 (4.5.2) was released and EclipseCodeFormatter does not handle new changes.

Are you planning to implement this feature soon ?

Thanks !

**Comment by krasa** [comment]
yes

**Comment by krasa** [comment]
Now i just need to reimplement import sorter https://github.com/krasa/EclipseCodeFormatter/issues/90#issuecomment-210694668

**Comment by krasa** [comment]
done, you can try it from here:
https://github.com/krasa/EclipseCodeFormatter/releases/download/15.5.132.637.0/EclipseFormatter.zip

**Comment by nicou50** [comment]
cool ! Thanks a alot. Going to try it tomorrow.

**Comment by nicou50** [comment]
A big thanks you. Working like a charm !
