### ISSUE TITLE
Eclipse code formatter not showing in IntelliJ Preferences if no project is open

### ISSUE THREAD

**Issue by rajsrivastav1919** [krasa/EclipseCodeFormatter#93]
Eclipse code formatter not showing in IntelliJ Preferences after the latest update if no project is open.
Earlier it was possible to set that plugin at that point so that all projects follow the same plugin settings.

Details that may be required -
IntelliJ IDEA version: 2016.1.1 
Plugin version: 15.5.132.637.1

**Comment by krasa** [comment]
It was never visible without a project opened. 
Not sure if I can do anything about it, but either way, profiles are shared, so you can modify them when you have a project opened and it will propagate to all projects - opened or closed.

**Comment by rajsrivastav1919** [comment]
Yeah that is fine, not a big issue. But, it was available before hence I thought it should still be there,
