### ISSUE TITLE
Problem with unshelve changes

### ISSUE THREAD

**Issue by bgranvea** [krasa/EclipseCodeFormatter#96]
I've just tried to unshelve changes. I've got multiple messages "XXX formatted successfully by Eclipse code formatter", always on the same files and the IDE becomes very sluggish.

I end up by restarting the IDE which was becoming unusable.

This happens only since I've upgraded to the latest version.

**Comment by krasa** [comment]
Cannot reproduce it, nothing is formatted when I unshelve things.

**Comment by bgranvea** [comment]
hum ok I try to find a test case to reproduce.

**Comment by krasa** [comment]
https://github.com/krasa/EclipseCodeFormatter/issues/95#issuecomment-219024998
