### ISSUE TITLE
Importorder file is not applied correctly

### ISSUE THREAD

**Issue by cooltea713705** [krasa/EclipseCodeFormatter#97]
[importorder-issue.zip](https://github.com/krasa/EclipseCodeFormatter/files/294427/importorder-issue.zip)

The attached java file is not formatted correctly by the Eclipse Code Formatter: the import statements are not ordered according to the attached importorder file (which is provided in the Eclipse Code Formatter plugin configuration), the import java... statement keeps showing up before the other imports when it is expected to come last.

Eclipse Mars 2 formats the file correctly when the same importorder file is imported.

**Comment by krasa** [comment]
Thanks! Fixed.
